using System.Text;

// Demonstrates code generation patterns with StringBuilder
Console.WriteLine("=== Basic StringBuilder Code Generation ===");

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated/>");
sb.AppendLine("namespace MyApp.Generated;");
sb.AppendLine();
sb.AppendLine("public static class Registry");
sb.AppendLine("{");
sb.AppendLine("    public static string[] Types => [");
sb.AppendLine("        \"OrderService\",");
sb.AppendLine("        \"UserService\",");
sb.AppendLine("    ];");
sb.AppendLine("}");

Console.WriteLine(sb.ToString());

// IndentedStringBuilder pattern
Console.WriteLine("=== IndentedStringBuilder Pattern ===");

var writer = new IndentedStringBuilder();
writer.AppendLine("// <auto-generated/>");
writer.AppendLine("namespace MyApp.Generated;");
writer.AppendLine();
writer.AppendLine("public static class ServiceLocator");
writer.OpenBrace();
{
    writer.AppendLine("public static IServiceProvider Build()");
    writer.OpenBrace();
    {
        writer.AppendLine("var services = new ServiceCollection();");
        foreach (var service in new[] { "OrderService", "UserService", "ProductService" })
        {
            writer.AppendLine($"services.AddScoped<{service}>();");
        }
        writer.AppendLine("return services.BuildServiceProvider();");
    }
    writer.CloseBrace();
}
writer.CloseBrace();

Console.WriteLine(writer.ToString());

/// <summary>
/// Simple indented string builder for source generation.
/// </summary>
public class IndentedStringBuilder
{
    private readonly StringBuilder _sb = new();
    private int _indent;

    public IndentedStringBuilder AppendLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
            _sb.AppendLine();
        else
            _sb.AppendLine($"{new string(' ', _indent * 4)}{line}");
        return this;
    }

    public IndentedStringBuilder OpenBrace()
    {
        AppendLine("{");
        _indent++;
        return this;
    }

    public IndentedStringBuilder CloseBrace()
    {
        _indent--;
        AppendLine("}");
        return this;
    }

    public override string ToString() => _sb.ToString();
}
