using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace VerifySnapshotTesting.Generator;

[Generator]
public class SnapshotGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoEqualsAttribute.g.cs", """
                // <auto-generated/>
                namespace VerifySnapshotTesting.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoEqualsAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "VerifySnapshotTesting.Generated.AutoEqualsAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var props = symbol.GetMembers()
                        .OfType<IPropertySymbol>()
                        .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                        .Select(p => p.Name)
                        .ToArray();
                    return (symbol.Name, Ns: symbol.ContainingNamespace.ToDisplayString(), Props: props);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var comparisons = string.Join("\n            && ", data.Props.Select(p =>
                $"this.{p} == other.{p}"));

            ctx.AddSource($"{data.Name}_Equals.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Ns}};

                public partial class {{data.Name}} : System.IEquatable<{{data.Name}}>
                {
                    public bool Equals({{data.Name}}? other)
                    {
                        if (other is null) return false;
                        return {{(comparisons.Length > 0 ? comparisons : "true")}};
                    }

                    public override bool Equals(object? obj) => Equals(obj as {{data.Name}});

                    public override int GetHashCode()
                        => System.HashCode.Combine({{string.Join(", ", data.Props)}});
                }
                """);
        });
    }
}
