using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace IncrementalCaching.Generator;

/// <summary>
/// Demonstrates incremental caching through value equality.
/// The generator only re-runs when the extracted data actually changes.
/// </summary>
[Generator]
public class CachingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("CachedAttribute.g.cs", """
                // <auto-generated/>
                namespace IncrementalCaching.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class CachedAttribute : System.Attribute { }
                """);
        });

        // The key to caching: extract only the data you need into an equatable type
        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "IncrementalCaching.Generated.CachedAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    // Return a value-equatable record — enables cache hits
                    return new ClassModel(
                        symbol.Name,
                        symbol.ContainingNamespace.ToDisplayString());
                });

        context.RegisterSourceOutput(pipeline, static (ctx, model) =>
        {
            ctx.AddSource($"{model.Name}_Cached.g.cs", $$"""
                // <auto-generated/>
                namespace {{model.Namespace}};

                public partial class {{model.Name}}
                {
                    /// <summary>Cached metadata generated at compile time.</summary>
                    public static string TypeName => "{{model.Name}}";
                    public static string TypeNamespace => "{{model.Namespace}}";
                }
                """);
        });
    }

    // Value equality via record enables incremental caching
    private sealed record ClassModel(string Name, string Namespace);
}
