using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace UnitTestingSetup.Generator;

[Generator]
public class SimpleGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoNameAttribute.g.cs", """
                // <auto-generated/>
                namespace UnitTestingSetup.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoNameAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "UnitTestingSetup.Generated.AutoNameAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    return (symbol.Name, Namespace: symbol.ContainingNamespace.ToDisplayString());
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            ctx.AddSource($"{data.Name}_Name.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Namespace}};

                public partial class {{data.Name}}
                {
                    public static string TypeName => "{{data.Name}}";
                }
                """);
        });
    }
}
