using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GenericTypes.Generator;

[Generator]
public class GenericTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoTypeInfoAttribute.g.cs", """
                // <auto-generated/>
                namespace GenericTypes.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoTypeInfoAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "GenericTypes.Generated.AutoTypeInfoAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var typeParams = symbol.TypeParameters
                        .Select(tp => new TypeParamData(
                            tp.Name,
                            tp.ConstraintTypes.Select(ct => ct.ToDisplayString()).ToArray()))
                        .ToArray();
                    var typeParamNames = symbol.TypeParameters.Select(tp => tp.Name).ToArray();

                    return new GenericClassData(
                        symbol.Name,
                        symbol.ContainingNamespace.ToDisplayString(),
                        typeParamNames,
                        typeParams);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var typeParamList = data.TypeParameterNames.Length > 0
                ? $"<{string.Join(", ", data.TypeParameterNames)}>"
                : "";

            var typeInfoEntries = data.TypeParameters
                .Select(tp =>
                {
                    var constraints = tp.Constraints.Length > 0
                        ? string.Join(", ", tp.Constraints)
                        : "none";
                    return $"        \"{tp.Name}: [{constraints}]\"";
                });
            var typeInfoList = string.Join(",\n", typeInfoEntries);

            ctx.AddSource($"{data.Name}_TypeInfo.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Namespace}};

                public partial class {{data.Name}}{{typeParamList}}
                {
                    public static string[] TypeParameterInfo => [
                {{typeInfoList}}
                    ];

                    public static int GenericArity => {{data.TypeParameterNames.Length}};
                }
                """);
        });
    }

    private sealed record TypeParamData(string Name, string[] Constraints);
    private sealed record GenericClassData(
        string Name, string Namespace, string[] TypeParameterNames, TypeParamData[] TypeParameters);
}
