using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EntityIdGenerator.Generator;

[Generator]
public class EntityIdSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("EntityIdAttribute.g.cs", """
                // <auto-generated/>
                namespace EntityIdGenerator.Generated;

                [System.AttributeUsage(System.AttributeTargets.Struct)]
                public class EntityIdAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "EntityIdGenerator.Generated.EntityIdAttribute",
                predicate: static (node, _) => node is StructDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    return (symbol.Name, Ns: symbol.ContainingNamespace.ToDisplayString());
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            ctx.AddSource($"{data.Name}.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Ns}};

                public readonly partial struct {{data.Name}} : System.IEquatable<{{data.Name}}>, System.IComparable<{{data.Name}}>
                {
                    public string Value { get; }

                    private {{data.Name}}(string value) => Value = value;

                    public static {{data.Name}} New() => new(System.Guid.NewGuid().ToString("N"));
                    public static {{data.Name}} From(string value) => new(value);

                    public bool Equals({{data.Name}} other) => Value == other.Value;
                    public override bool Equals(object? obj) => obj is {{data.Name}} other && Equals(other);
                    public override int GetHashCode() => Value?.GetHashCode() ?? 0;
                    public int CompareTo({{data.Name}} other) => string.Compare(Value, other.Value, System.StringComparison.Ordinal);
                    public override string ToString() => Value ?? "";

                    public static bool operator ==({{data.Name}} left, {{data.Name}} right) => left.Equals(right);
                    public static bool operator !=({{data.Name}} left, {{data.Name}} right) => !left.Equals(right);
                }
                """);
        });
    }
}
