using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TestScenarios.Generator;

[Generator]
public class RangeCheckGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("RangeAttribute.g.cs", """
                // <auto-generated/>
                namespace TestScenarios.Generated;

                [System.AttributeUsage(System.AttributeTargets.Property)]
                public class RangeAttribute(int min, int max) : System.Attribute
                {
                    public int Min { get; } = min;
                    public int Max { get; } = max;
                }

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class ValidateRangeAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "TestScenarios.Generated.ValidateRangeAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var rangeProps = symbol.GetMembers()
                        .OfType<IPropertySymbol>()
                        .SelectMany(p =>
                        {
                            var attr = p.GetAttributes().FirstOrDefault(a =>
                                a.AttributeClass?.Name == "RangeAttribute");
                            if (attr is null) return Enumerable.Empty<RangeProp>();
                            var min = (int)attr.ConstructorArguments[0].Value!;
                            var max = (int)attr.ConstructorArguments[1].Value!;
                            return [new RangeProp(p.Name, min, max)];
                        })
                        .ToArray();
                    return new ClassData(symbol.Name, symbol.ContainingNamespace.ToDisplayString(), rangeProps);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var checks = data.Properties.Select(p =>
                $"            if ({p.Name} < {p.Min} || {p.Name} > {p.Max})\n                errors.Add(\"{p.Name} must be between {p.Min} and {p.Max}, got \" + {p.Name});");

            ctx.AddSource($"{data.Name}_Validate.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Namespace}};

                public partial class {{data.Name}}
                {
                    public string[] Validate()
                    {
                        var errors = new System.Collections.Generic.List<string>();
                {{string.Join("\n", checks)}}
                        return errors.ToArray();
                    }
                }
                """);
        });
    }

    private sealed record RangeProp(string Name, int Min, int Max);
    private sealed record ClassData(string Name, string Namespace, RangeProp[] Properties);
}
