using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ValidationGenerator.Generator;

[Generator]
public class ValidationSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("Attributes.g.cs", """
                // <auto-generated/>
                namespace ValidationGenerator.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoValidateAttribute : System.Attribute { }

                [System.AttributeUsage(System.AttributeTargets.Property)]
                public class RequiredAttribute : System.Attribute { }

                [System.AttributeUsage(System.AttributeTargets.Property)]
                public class MaxLengthAttribute : System.Attribute
                {
                    public MaxLengthAttribute(int length) { Length = length; }
                    public int Length { get; }
                }

                [System.AttributeUsage(System.AttributeTargets.Property)]
                public class RangeAttribute : System.Attribute
                {
                    public RangeAttribute(double min, double max) { Min = min; Max = max; }
                    public double Min { get; }
                    public double Max { get; }
                }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ValidationGenerator.Generated.AutoValidateAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var props = symbol.GetMembers()
                        .OfType<IPropertySymbol>()
                        .Select(p => new PropData(
                            p.Name,
                            p.Type.ToDisplayString(),
                            p.GetAttributes().Select(a => new AttrData(
                                a.AttributeClass?.Name ?? "",
                                a.ConstructorArguments.Select(ca => ca.Value).ToArray()
                            )).ToArray()
                        ))
                        .ToArray();
                    return new ClassData(symbol.Name, symbol.ContainingNamespace.ToDisplayString(), props);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var checks = new System.Collections.Generic.List<string>();
            foreach (var prop in data.Properties)
            {
                foreach (var attr in prop.Attributes)
                {
                    switch (attr.Name)
                    {
                        case "RequiredAttribute":
                            if (prop.Type == "string")
                                checks.Add($"        if (string.IsNullOrWhiteSpace({prop.Name})) errors.Add(\"{prop.Name} is required.\");");
                            else
                                checks.Add($"        if ({prop.Name} is null) errors.Add(\"{prop.Name} is required.\");");
                            break;
                        case "MaxLengthAttribute":
                            var maxLen = attr.Args.Length > 0 ? attr.Args[0] : 0;
                            checks.Add($"        if ({prop.Name}?.Length > {maxLen}) errors.Add(\"{prop.Name} must be at most {maxLen} characters.\");");
                            break;
                        case "RangeAttribute":
                            var min = attr.Args.Length > 0 ? attr.Args[0] : 0;
                            var max = attr.Args.Length > 1 ? attr.Args[1] : 0;
                            checks.Add($"        if ({prop.Name} < {min} || {prop.Name} > {max}) errors.Add(\"{prop.Name} must be between {min} and {max}.\");");
                            break;
                    }
                }
            }

            ctx.AddSource($"{data.Name}_Validate.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Namespace}};

                public partial class {{data.Name}}
                {
                    public string[] Validate()
                    {
                        var errors = new System.Collections.Generic.List<string>();
                {{string.Join("\n", checks)}}
                        return errors.ToArray();
                    }
                }
                """);
        });
    }

    private sealed record AttrData(string Name, object?[] Args);
    private sealed record PropData(string Name, string Type, AttrData[] Attributes);
    private sealed record ClassData(string Name, string Namespace, PropData[] Properties);
}
