using Microsoft.CodeAnalysis;

namespace IncrementalGenerator.Generator;

[Generator]
public class MinimalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Register post-initialization output (no input needed)
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("GeneratorInfo.g.cs", """
                // <auto-generated/>
                namespace IncrementalGenerator.Generated;

                public static class GeneratorInfo
                {
                    public static string Name => "MinimalGenerator";
                    public static string Version => "1.0.0";
                }
                """);
        });

        // Step 2: Set up incremental pipeline
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                transform: static (ctx, _) => (Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax)ctx.Node)
            .Where(static c => c.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PublicKeyword));

        context.RegisterSourceOutput(classDeclarations, static (ctx, classDecl) =>
        {
            var className = classDecl.Identifier.Text;
            ctx.AddSource($"{className}_Info.g.cs", $$"""
                // <auto-generated/>
                namespace IncrementalGenerator.Generated;

                public static partial class ClassRegistry
                {
                    public static string {{className}}Info => "Discovered: {{className}}";
                }
                """);
        });
    }
}
