using Microsoft.CodeAnalysis;

namespace HelloWorldGenerator.Generator;

[Generator]
public class HelloWorldSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("HelloWorld.g.cs", """
                // <auto-generated/>
                namespace HelloWorldGenerator.Generated;

                public static class HelloWorld
                {
                    public static string Greet(string name)
                        => $"Hello, {name}! (Generated at compile time)";
                }
                """);
        });
    }
}
