<#
.SYNOPSIS
    Extract API changes by building current branch and generating Public API using PublicApiGenerator

.DESCRIPTION
    This script builds all Functorium projects and generates Public API Surface files
    using PublicApiGenerator.Tool (open source alternative to GenAPI).

.EXAMPLE
    .\extract-api-changes.ps1
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

# Get script directory and set paths
$ToolsDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AnalysisDir = Join-Path $ToolsDir "analysis-output"
$ApiChangesDir = Join-Path $AnalysisDir "api-changes-build-current"
$GitRoot = git rev-parse --show-toplevel 2>$null
if (-not $GitRoot) {
    $GitRoot = Split-Path -Parent (Split-Path -Parent $ToolsDir)
}

Write-Host "Extracting API changes by building current branch" -ForegroundColor Cyan
Write-Host "Using PublicApiGenerator.Tool for API generation..." -ForegroundColor Yellow

$ScriptStartTime = Get-Date

# Create output directory
if (Test-Path $ApiChangesDir) {
    Remove-Item -Recurse -Force $ApiChangesDir
}
New-Item -ItemType Directory -Path $ApiChangesDir -Force | Out-Null

# Get current branch
$CurrentBranch = git branch --show-current 2>$null
if (-not $CurrentBranch) {
    $CurrentBranch = git rev-parse HEAD 2>$null
}

Write-Host "Current branch: $CurrentBranch" -ForegroundColor Green

function Main {
    $StartTime = Get-Date

    Write-Host ""
    Write-Host "Starting API Changes Detection Script" -ForegroundColor Cyan
    Write-Host "   Current Branch: $CurrentBranch"
    Write-Host "   Output Dir: $ApiChangesDir"
    Write-Host "   Timestamp: $(Get-Date)"
    Write-Host ""

    Push-Location $GitRoot
    try {
        # Build the ApiGenerator tool
        Write-Host "Building ApiGenerator tool..." -ForegroundColor Yellow
        $ApiGeneratorProj = Join-Path $ToolsDir "ApiGenerator.csproj"
        $ApiGeneratorDir = Join-Path $ToolsDir "bin\ApiGenerator"
        & dotnet build $ApiGeneratorProj -c Release -o $ApiGeneratorDir 2>&1 | Out-Null
        $ApiGeneratorExe = Join-Path $ApiGeneratorDir "ApiGenerator.dll"

        if (-not (Test-Path $ApiGeneratorExe)) {
            Write-Host "Error: Failed to build ApiGenerator" -ForegroundColor Red
            exit 1
        }
        Write-Host "    ApiGenerator built successfully" -ForegroundColor Green

        # Find all projects to generate API for
        Write-Host "Publishing and generating Public API files..." -ForegroundColor Cyan

        $SrcDir = Join-Path $GitRoot "Src"
        $ApiOutputDir = Join-Path $ApiChangesDir "api-files"
        New-Item -ItemType Directory -Path $ApiOutputDir -Force | Out-Null

        # Find project files (excluding test projects)
        $ProjectFiles = Get-ChildItem -Path $SrcDir -Recurse -Filter "*.csproj" |
            Where-Object {
                $_.Name -notlike "*.Tests.*" -and
                ($_.Name -like "Functorium*.csproj")
            } |
            Sort-Object Name -Unique

        $TotalFilesFound = 0
        $GeneratedApiFiles = @()

        foreach ($Project in $ProjectFiles) {
            $AssemblyName = [System.IO.Path]::GetFileNameWithoutExtension($Project.Name)
            $OutputFile = Join-Path $ApiOutputDir "$AssemblyName.cs"
            $PublishDir = Join-Path $Project.DirectoryName "bin\publish"

            Write-Host "    Publishing: $AssemblyName" -ForegroundColor Yellow

            try {
                # Publish the project to get all dependencies
                & dotnet publish $Project.FullName -c Release -o $PublishDir 2>&1 | Out-Null

                $DllPath = Join-Path $PublishDir "$AssemblyName.dll"
                if (-not (Test-Path $DllPath)) {
                    Write-Host "      DLL not found after publish: $DllPath" -ForegroundColor Yellow
                    continue
                }

                Write-Host "    Generating API for: $AssemblyName" -ForegroundColor Yellow

                # Use custom ApiGenerator to generate API
                $ApiOutput = & dotnet $ApiGeneratorExe $DllPath "-" 2>&1

                if ($LASTEXITCODE -eq 0 -and $ApiOutput) {
                    # Add header and save
                    $ApiContent = @()
                    $ApiContent += "//------------------------------------------------------------------------------"
                    $ApiContent += "// <auto-generated>"
                    $ApiContent += "//     This code was generated by PublicApiGenerator."
                    $ApiContent += "//     Assembly: $AssemblyName"
                    $ApiContent += "//     Generated at: $(Get-Date)"
                    $ApiContent += "// </auto-generated>"
                    $ApiContent += "//------------------------------------------------------------------------------"
                    $ApiContent += ""
                    $ApiContent += $ApiOutput

                    $ApiContent | Out-File -FilePath $OutputFile -Encoding UTF8
                    $GeneratedApiFiles += $OutputFile
                    $TotalFilesFound++
                    Write-Host "      Created: $OutputFile" -ForegroundColor Green
                } else {
                    Write-Host "      Skipped (no public API or error): $ApiOutput" -ForegroundColor Yellow
                }
            } catch {
                Write-Host "      Error: $_" -ForegroundColor Red
            }
        }

        Write-Host "    Generated $TotalFilesFound API files" -ForegroundColor Green

        # Create uber file
        Write-Host "Creating uber API file..." -ForegroundColor Cyan
        $UberFile = Join-Path $ApiChangesDir "all-api-changes.txt"

        $UberContent = @()
        $UberContent += "# All API Files - Uber File"
        $UberContent += "# Generated from: $CurrentBranch"
        $UberContent += "# Generated at: $(Get-Date)"
        $UberContent += "# Generated by: PublicApiGenerator.Tool"
        $UberContent += "# Total API files included: $TotalFilesFound"
        $UberContent += ""

        foreach ($ApiFile in $GeneratedApiFiles) {
            $AssemblyName = [System.IO.Path]::GetFileNameWithoutExtension($ApiFile)

            $UberContent += "======================================"
            $UberContent += "API FILE: $ApiFile"
            $UberContent += "ASSEMBLY: $AssemblyName"
            $UberContent += "======================================"
            $UberContent += ""

            try {
                $FileContent = Get-Content $ApiFile -Raw -ErrorAction Stop
                $UberContent += $FileContent
            } catch {
                $UberContent += "# Error reading file $ApiFile"
            }
            $UberContent += ""
            $UberContent += ""
        }

        $UberContent | Out-File -FilePath $UberFile -Encoding UTF8
        Write-Host "    Uber API file created: $UberFile" -ForegroundColor Green

        # Generate git diff for API files
        Write-Host "Generating git diff..." -ForegroundColor Cyan
        $ApiDiffPath = Join-Path $ApiChangesDir "api-changes-diff.txt"

        # Check for any existing api files in git
        $DiffContent = git diff HEAD -- 'Src/*/api/*.cs' 2>$null
        if ($DiffContent) {
            $DiffContent | Out-File -FilePath $ApiDiffPath -Encoding UTF8
        } else {
            "# No tracked API file changes (API files are newly generated)" | Out-File -FilePath $ApiDiffPath -Encoding UTF8
        }

        # Create summary report
        $SummaryContent = @"
# API Files Summary

Generated from: $CurrentBranch
Generated at: $(Get-Date)
Generated by: PublicApiGenerator.Tool v11.4.6

## Overview

This document contains all Public API definitions from the Functorium repository.

## Results

- **Total API Files Generated**: $TotalFilesFound

## API Files List

"@

        foreach ($ApiFile in $GeneratedApiFiles) {
            $AssemblyName = [System.IO.Path]::GetFileNameWithoutExtension($ApiFile)
            $SummaryContent += "- **$AssemblyName**: ``$ApiFile```n"
        }

        $SummaryContent | Out-File -FilePath (Join-Path $ApiChangesDir "api-changes-summary.md") -Encoding UTF8

        # Write projects list
        $ProjectsList = Join-Path $ApiChangesDir "projects.txt"
        $ProjectFiles | ForEach-Object { $_.Name } | Out-File -FilePath $ProjectsList -Encoding UTF8

    } finally {
        Pop-Location
    }

    $EndTime = Get-Date
    $TotalTime = ($EndTime - $StartTime).TotalSeconds

    Write-Host ""
    Write-Host "API Files Collection completed successfully!" -ForegroundColor Green
    Write-Host "   Current Branch: $CurrentBranch"
    Write-Host "   Output: $ApiChangesDir/"
    Write-Host "   Total API Files: $TotalFilesFound"
    Write-Host "   Total Time: $([math]::Round($TotalTime, 1))s"
    Write-Host "   Summary: $ApiChangesDir/api-changes-summary.md"
    Write-Host "   Uber API File: $ApiChangesDir/all-api-changes.txt"
    Write-Host "   API Files: $ApiChangesDir/api-files/"
    Write-Host ""
}

# Run the main function
Main
