#!/bin/bash

# Extract API changes by building current branch and generating Public API using PublicApiGenerator
# Usage: ./extract-api-changes.sh

set -e

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANALYSIS_DIR="$TOOLS_DIR/analysis-output"
API_CHANGES_DIR="$ANALYSIS_DIR/api-changes-build-current"

echo "Extracting API changes by building current branch"
echo "Using PublicApiGenerator.Tool for API generation..."

# Start total timing
SCRIPT_START_TIME=$(date +%s)

# Get git root
GIT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_ROOT"

# Get current branch for reporting
CURRENT_BRANCH=$(git branch --show-current)
if [ -z "$CURRENT_BRANCH" ]; then
    CURRENT_BRANCH=$(git rev-parse HEAD)
fi

echo "Current branch: $CURRENT_BRANCH"

# Main function
main() {
    start_time=$(date +%s)

    echo ""
    echo "Starting API Changes Detection Script"
    echo "   Current Branch: $CURRENT_BRANCH"
    echo "   Output Dir: $API_CHANGES_DIR"
    echo "   Timestamp: $(date)"
    echo ""

    # Clean output directory
    echo "Cleaning output directory..."
    rm -rf "$API_CHANGES_DIR"
    mkdir -p "$API_CHANGES_DIR"
    mkdir -p "$API_CHANGES_DIR/api-files"
    echo "Output directory ready: $API_CHANGES_DIR"

    # Build the ApiGenerator tool
    echo "Building ApiGenerator tool..."
    local api_generator_proj="$TOOLS_DIR/ApiGenerator.csproj"
    local api_generator_dir="$TOOLS_DIR/bin/ApiGenerator"
    dotnet build "$api_generator_proj" -c Release -o "$api_generator_dir" 2>&1 | grep -v "^  " || true
    local api_generator_exe="$api_generator_dir/ApiGenerator.dll"

    if [ ! -f "$api_generator_exe" ]; then
        echo "Error: Failed to build ApiGenerator"
        exit 1
    fi
    echo "    ApiGenerator built successfully"

    # Find all projects to generate API for
    echo "Publishing and generating Public API files..."

    local src_dir="$GIT_ROOT/Src"
    local api_output_dir="$API_CHANGES_DIR/api-files"
    local total_files_found=0
    local generated_api_files=()

    # Find project files (excluding test projects)
    while IFS= read -r project_file; do
        if [ -n "$project_file" ] && [ -f "$project_file" ]; then
            local assembly_name=$(basename "$project_file" .csproj)
            local project_dir=$(dirname "$project_file")
            local publish_dir="$project_dir/bin/publish"
            local output_file="$api_output_dir/$assembly_name.cs"

            echo "    Publishing: $assembly_name"

            # Publish the project to get all dependencies
            dotnet publish "$project_file" -c Release -o "$publish_dir" 2>&1 | grep -v "^  " || true

            local dll_path="$publish_dir/$assembly_name.dll"
            if [ ! -f "$dll_path" ]; then
                echo "      DLL not found after publish: $dll_path"
                continue
            fi

            echo "    Generating API for: $assembly_name"

            # Use custom ApiGenerator to generate API
            local api_output
            api_output=$(dotnet "$api_generator_exe" "$dll_path" "-" 2>&1) || true

            if [ -n "$api_output" ] && [ "$api_output" != "" ] && [[ ! "$api_output" =~ ^Error ]]; then
                # Add header and save
                {
                    echo "//------------------------------------------------------------------------------"
                    echo "// <auto-generated>"
                    echo "//     This code was generated by PublicApiGenerator."
                    echo "//     Assembly: $assembly_name"
                    echo "//     Generated at: $(date)"
                    echo "// </auto-generated>"
                    echo "//------------------------------------------------------------------------------"
                    echo ""
                    echo "$api_output"
                } > "$output_file"

                generated_api_files+=("$output_file")
                ((total_files_found++))
                echo "      Created: $output_file"
            else
                echo "      Skipped (no public API or error)"
            fi
        fi
    done < <(find "$src_dir" -name "Functorium*.csproj" ! -name "*.Tests.*" 2>/dev/null | sort -u)

    echo "    Generated $total_files_found API files"

    # Create uber file
    echo "Creating uber API file..."
    local uber_file="$API_CHANGES_DIR/all-api-changes.txt"

    {
        echo "# All API Files - Uber File"
        echo "# Generated from: $CURRENT_BRANCH"
        echo "# Generated at: $(date)"
        echo "# Generated by: PublicApiGenerator.Tool"
        echo "# Total API files included: $total_files_found"
        echo ""

        for api_file in "${generated_api_files[@]}"; do
            if [ -f "$api_file" ]; then
                local assembly_name=$(basename "$api_file" .cs)
                echo "======================================"
                echo "API FILE: $api_file"
                echo "ASSEMBLY: $assembly_name"
                echo "======================================"
                echo ""
                cat "$api_file" 2>/dev/null || echo "# Error reading file $api_file"
                echo ""
                echo ""
            fi
        done
    } > "$uber_file"

    echo "    Uber API file created: $uber_file"

    # Generate git diff for API files
    echo "Generating git diff..."
    local api_diff_path="$API_CHANGES_DIR/api-changes-diff.txt"

    git diff HEAD -- 'Src/*/api/*.cs' > "$api_diff_path" 2>/dev/null || echo "# No tracked API file changes (API files are newly generated)" > "$api_diff_path"

    # Create summary report
    cat > "$API_CHANGES_DIR/api-changes-summary.md" << EOF
# API Files Summary

Generated from: $CURRENT_BRANCH
Generated at: $(date)
Generated by: PublicApiGenerator.Tool v11.4.6

## Overview

This document contains all Public API definitions from the Functorium repository.

## Results

- **Total API Files Generated**: $total_files_found

## API Files List

EOF

    for api_file in "${generated_api_files[@]}"; do
        local assembly_name=$(basename "$api_file" .cs)
        echo "- **$assembly_name**: \`$api_file\`" >> "$API_CHANGES_DIR/api-changes-summary.md"
    done

    # Write projects list
    find "$src_dir" -path "*/bin/Release/*" -name "Functorium*.dll" ! -name "*.Tests.*" ! -name "*.resources.dll" 2>/dev/null | xargs -I{} basename {} | sort -u > "$API_CHANGES_DIR/projects.txt"

    end_time=$(date +%s)
    total_time=$((end_time - start_time))

    echo ""
    echo "API Files Collection completed successfully!"
    echo "   Current Branch: $CURRENT_BRANCH"
    echo "   Output: $API_CHANGES_DIR/"
    echo "   Total API Files: $total_files_found"
    echo "   Total Time: ${total_time}s"
    echo "   Summary: $API_CHANGES_DIR/api-changes-summary.md"
    echo "   Uber API File: $API_CHANGES_DIR/all-api-changes.txt"
    echo "   API Files: $API_CHANGES_DIR/api-files/"
    echo ""
}

# Run the main function
main "$@"
