global using LanguageExt;
global using LanguageExt.Common;
global using static LanguageExt.Prelude;
global using Xunit;
global using Shouldly;
global using NSubstitute;
global using Functorium.Applications.Cqrs;
global using Functorium.Applications.Pipelines;
global using CqrsPipeline.Demo;
global using CqrsPipeline.Demo.Domain;
global using CqrsPipeline.Demo.Usecases;
