using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ConstructorHandling.Generator;

[Generator]
public class ConstructorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoFactoryAttribute.g.cs", """
                // <auto-generated/>
                namespace ConstructorHandling.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoFactoryAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ConstructorHandling.Generated.AutoFactoryAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var ctor = symbol.Constructors
                        .Where(c => !c.IsImplicitlyDeclared)
                        .OrderByDescending(c => c.Parameters.Length)
                        .FirstOrDefault();

                    var parameters = ctor?.Parameters
                        .Select(p => new ParamData(
                            p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            p.Name))
                        .ToArray() ?? [];

                    return new ClassData(
                        symbol.Name,
                        symbol.ContainingNamespace.ToDisplayString(),
                        parameters);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var paramList = string.Join(", ", data.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var argList = string.Join(", ", data.Parameters.Select(p => p.Name));

            ctx.AddSource($"{data.Name}_Factory.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Namespace}};

                public partial class {{data.Name}}
                {
                    public static {{data.Name}} Create({{paramList}})
                        => new({{argList}});
                }
                """);
        });
    }

    private sealed record ParamData(string Type, string Name);
    private sealed record ClassData(string Name, string Namespace, ParamData[] Parameters);
}
