using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LoggerMessageLimits.Generator;

/// <summary>
/// Demonstrates the LoggerMessage.Define 6-parameter limit and fallback strategy.
/// </summary>
[Generator]
public class LoggerLimitGenerator : IIncrementalGenerator
{
    private const int MaxLoggerMessageParams = 6;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoLogAttribute.g.cs", """
                // <auto-generated/>
                namespace LoggerMessageLimits.Generated;

                [System.AttributeUsage(System.AttributeTargets.Method)]
                public class AutoLogAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "LoggerMessageLimits.Generated.AutoLogAttribute",
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var method = (IMethodSymbol)ctx.TargetSymbol;
                    var containingType = method.ContainingType;
                    return new MethodData(
                        containingType.Name,
                        containingType.ContainingNamespace.ToDisplayString(),
                        method.Name,
                        method.Parameters.Select(p => new ParamInfo(
                            p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                            p.Name)).ToArray());
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var useDefine = data.Parameters.Length <= MaxLoggerMessageParams;
            var strategy = useDefine ? "LoggerMessage.Define" : "LoggerMessage (fallback)";
            var paramList = string.Join(", ", data.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var templateParts = string.Join(", ", data.Parameters.Select(p => $"{{{p.Name}}}"));

            ctx.AddSource($"{data.ClassName}_{data.MethodName}_Log.g.cs", $$"""
                // <auto-generated/>
                // Strategy: {{strategy}} ({{data.Parameters.Length}} parameters)
                namespace {{data.Namespace}};

                public partial class {{data.ClassName}}
                {
                    public static string {{data.MethodName}}LogMessage({{paramList}})
                        => $"{{data.MethodName}}: {{templateParts}}";
                }
                """);
        });
    }

    private sealed record ParamInfo(string Type, string Name);
    private sealed record MethodData(
        string ClassName, string Namespace, string MethodName, ParamInfo[] Parameters);
}
