using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using static Functorium.Adapters.SourceGenerator.Abstractions.Constants;
using static Functorium.Adapters.SourceGenerator.Abstractions.Selectors;

namespace Functorium.Adapters.SourceGenerator.Generators.EntityIdGenerator;

/// <summary>
/// [GenerateEntityId] 속성이 붙은 Entity 클래스에 대해
/// EntityId, EntityIdComparer, EntityIdConverter를 자동 생성하는 소스 생성기.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EntityIdGenerator()
    : IncrementalGeneratorBase<EntityIdInfo>(
        RegisterSourceProvider,
        Generate,
        AttachDebugger: false)
{
    private const string AttributeName = "GenerateEntityId";
    private const string AttributeNamespace = "Functorium.Domains.SourceGenerator";
    private const string FullyQualifiedAttributeName = $"{AttributeNamespace}.{AttributeName}Attribute";
    private const string GenerateEntityIdAttributeFileName = "GenerateEntityIdAttribute.g.cs";

    public const string GenerateEntityIdAttribute = Header + """

        namespace Functorium.Domains.SourceGenerator;

        /// <summary>
        /// Entity 클래스에 이 속성을 적용하면 해당 Entity의 ID 타입이 자동으로 생성됩니다.
        /// 생성되는 타입: {EntityName}Id, {EntityName}IdComparer, {EntityName}IdConverter
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Generated by source generator.")]
        public class GenerateEntityIdAttribute : global::System.Attribute;
        """;

    private static IncrementalValuesProvider<EntityIdInfo> RegisterSourceProvider(
        IncrementalGeneratorInitializationContext context)
    {
        // 1단계: 고정 코드 생성 (Post-initialization)
        //  - GenerateEntityIdAttribute 정의
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                hintName: GenerateEntityIdAttributeFileName,
                sourceText: SourceText.From(GenerateEntityIdAttribute, Encoding.UTF8)));

        // 2단계: [GenerateEntityId] 속성이 붙은 클래스 필터링
        return context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: FullyQualifiedAttributeName,
                predicate: IsClass,
                transform: MapToEntityIdInfo)
            .Where(x => x != EntityIdInfo.None);
    }

    private static EntityIdInfo MapToEntityIdInfo(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
        {
            return EntityIdInfo.None;
        }

        cancellationToken.ThrowIfCancellationRequested();

        string entityName = classSymbol.Name;
        string @namespace = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : classSymbol.ContainingNamespace.ToString();

        string idTypeName = $"{entityName}Id";
        Location? location = context.TargetNode.GetLocation();

        return new EntityIdInfo(@namespace, entityName, idTypeName, location);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<EntityIdInfo> entityIdInfos)
    {
        foreach (var info in entityIdInfos)
        {
            StringBuilder sb = new();
            string source = GenerateEntityIdSource(info, sb);

            // 네임스페이스의 마지막 부분 추출
            string namespaceSuffix = string.Empty;
            if (!string.IsNullOrEmpty(info.Namespace))
            {
                var lastDotIndex = info.Namespace.LastIndexOf('.');
                if (lastDotIndex >= 0)
                {
                    namespaceSuffix = info.Namespace.Substring(lastDotIndex + 1) + ".";
                }
            }

            context.AddSource(
                $"{namespaceSuffix}{info.IdTypeName}.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateEntityIdSource(EntityIdInfo info, StringBuilder sb)
    {
        sb.Append(Header)
            .AppendLine()
            .AppendLine("using System.ComponentModel;")
            .AppendLine("using System.Diagnostics;")
            .AppendLine("using System.Text.Json;")
            .AppendLine("using System.Text.Json.Serialization;")
            .AppendLine()
            .AppendLine($"namespace {info.Namespace};")
            .AppendLine();

        // EntityId 구조체 생성
        GenerateEntityIdStruct(sb, info);

        // EntityIdComparer 생성
        GenerateEntityIdComparer(sb, info);

        // EntityIdConverter 생성
        GenerateEntityIdConverter(sb, info);

        return sb.ToString();
    }

    private static void GenerateEntityIdStruct(StringBuilder sb, EntityIdInfo info)
    {
        sb.AppendLine($"/// <summary>")
            .AppendLine($"/// {info.EntityName} Entity의 고유 식별자.")
            .AppendLine($"/// Ulid 기반으로 시간 순서 정렬이 가능합니다.")
            .AppendLine($"/// </summary>")
            .AppendLine("[DebuggerDisplay(\"{Value}\")]")
            .AppendLine($"[JsonConverter(typeof({info.IdTypeName}JsonConverter))]")
            .AppendLine($"[TypeConverter(typeof({info.IdTypeName}TypeConverter))]")
            .AppendLine($"public readonly partial record struct {info.IdTypeName} :")
            .AppendLine($"    global::Functorium.Domains.Entities.IEntityId<{info.IdTypeName}>,")
            .AppendLine($"    global::System.IParsable<{info.IdTypeName}>")
            .AppendLine("{")
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 타입 이름 상수.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public const string Name = \"{info.IdTypeName}\";")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 네임스페이스 상수.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public const string Namespace = \"{info.Namespace}\";")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 빈 값을 나타내는 상수.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public static readonly {info.IdTypeName} Empty = new(global::System.Ulid.Empty);")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// Ulid 값.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public global::System.Ulid Value {{ get; init; }}")
            .AppendLine()
            .AppendLine($"    private {info.IdTypeName}(global::System.Ulid id) => Value = id;")
            .AppendLine()
            .AppendLine("    #region Factory Methods")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 새로운 {info.IdTypeName}를 생성합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public static {info.IdTypeName} New() => new(global::System.Ulid.NewUlid());")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// Ulid로부터 {info.IdTypeName}를 생성합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public static {info.IdTypeName} Create(global::System.Ulid id) => new(id);")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 문자열로부터 {info.IdTypeName}를 생성합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    /// <exception cref=\"global::System.FormatException\">유효하지 않은 Ulid 형식인 경우</exception>")
            .AppendLine($"    public static {info.IdTypeName} Create(string id)")
            .AppendLine("    {")
            .AppendLine("        if (!global::System.Ulid.TryParse(id, out var ulid))")
            .AppendLine($"            throw new global::System.FormatException($\"Invalid {info.IdTypeName} format: {{id}}\");")
            .AppendLine($"        return new {info.IdTypeName}(ulid);")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    #endregion")
            .AppendLine()
            .AppendLine("    #region IComparable<T>")
            .AppendLine()
            .AppendLine($"    /// <inheritdoc />")
            .AppendLine($"    public int CompareTo({info.IdTypeName} other) => Value.CompareTo(other.Value);")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 두 {info.IdTypeName}를 비교합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public static bool operator <({info.IdTypeName} left, {info.IdTypeName} right) => left.CompareTo(right) < 0;")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 두 {info.IdTypeName}를 비교합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public static bool operator >({info.IdTypeName} left, {info.IdTypeName} right) => left.CompareTo(right) > 0;")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 두 {info.IdTypeName}를 비교합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public static bool operator <=({info.IdTypeName} left, {info.IdTypeName} right) => left.CompareTo(right) <= 0;")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 두 {info.IdTypeName}를 비교합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public static bool operator >=({info.IdTypeName} left, {info.IdTypeName} right) => left.CompareTo(right) >= 0;")
            .AppendLine()
            .AppendLine("    #endregion")
            .AppendLine()
            .AppendLine("    #region IParsable<T>")
            .AppendLine()
            .AppendLine($"    /// <inheritdoc />")
            .AppendLine($"    public static {info.IdTypeName} Parse(string s, global::System.IFormatProvider? provider) => Create(s);")
            .AppendLine()
            .AppendLine($"    /// <inheritdoc />")
            .AppendLine($"    public static bool TryParse(string? s, global::System.IFormatProvider? provider, out {info.IdTypeName} result)")
            .AppendLine("    {")
            .AppendLine("        if (s is null || !global::System.Ulid.TryParse(s, out var ulid))")
            .AppendLine("        {")
            .AppendLine("            result = Empty;")
            .AppendLine("            return false;")
            .AppendLine("        }")
            .AppendLine($"        result = new {info.IdTypeName}(ulid);")
            .AppendLine("        return true;")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    #endregion")
            .AppendLine()
            .AppendLine($"    /// <inheritdoc />")
            .AppendLine("    public override string ToString() => Value.ToString();")
            .AppendLine()
            .AppendLine("    #region JsonConverter")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// {info.IdTypeName}의 JSON 직렬화/역직렬화를 처리합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    internal sealed class {info.IdTypeName}JsonConverter : global::System.Text.Json.Serialization.JsonConverter<{info.IdTypeName}>")
            .AppendLine("    {")
            .AppendLine($"        /// <inheritdoc />")
            .AppendLine($"        public override {info.IdTypeName} Read(ref Utf8JsonReader reader, global::System.Type typeToConvert, JsonSerializerOptions options)")
            .AppendLine("        {")
            .AppendLine("            var value = reader.GetString();")
            .AppendLine("            return value is null ? Empty : Create(value);")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine($"        /// <inheritdoc />")
            .AppendLine($"        public override void Write(Utf8JsonWriter writer, {info.IdTypeName} value, JsonSerializerOptions options)")
            .AppendLine("        {")
            .AppendLine("            writer.WriteStringValue(value.Value.ToString());")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    #endregion")
            .AppendLine()
            .AppendLine("    #region TypeConverter")
            .AppendLine()
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// {info.IdTypeName}의 타입 변환을 처리합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    internal sealed class {info.IdTypeName}TypeConverter : global::System.ComponentModel.TypeConverter")
            .AppendLine("    {")
            .AppendLine($"        /// <inheritdoc />")
            .AppendLine("        public override bool CanConvertFrom(ITypeDescriptorContext? context, global::System.Type sourceType)")
            .AppendLine("        {")
            .AppendLine("            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine($"        /// <inheritdoc />")
            .AppendLine("        public override bool CanConvertTo(ITypeDescriptorContext? context, global::System.Type? destinationType)")
            .AppendLine("        {")
            .AppendLine("            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine($"        /// <inheritdoc />")
            .AppendLine("        public override object? ConvertFrom(ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value)")
            .AppendLine("        {")
            .AppendLine("            if (value is string str)")
            .AppendLine("            {")
            .AppendLine("                return Create(str);")
            .AppendLine("            }")
            .AppendLine("            return base.ConvertFrom(context, culture, value);")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine($"        /// <inheritdoc />")
            .AppendLine("        public override object? ConvertTo(ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType)")
            .AppendLine("        {")
            .AppendLine($"            if (value is {info.IdTypeName} id && destinationType == typeof(string))")
            .AppendLine("            {")
            .AppendLine("                return id.ToString();")
            .AppendLine("            }")
            .AppendLine("            return base.ConvertTo(context, culture, value, destinationType);")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    #endregion")
            .AppendLine("}")
            .AppendLine();
    }

    private static void GenerateEntityIdComparer(StringBuilder sb, EntityIdInfo info)
    {
        sb.AppendLine($"/// <summary>")
            .AppendLine($"/// EF Core ValueComparer for {info.IdTypeName}.")
            .AppendLine($"/// 변경 추적 및 스냅샷 비교에 사용됩니다.")
            .AppendLine($"/// </summary>")
            .AppendLine($"public sealed class {info.IdTypeName}Comparer : global::Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer<{info.IdTypeName}>")
            .AppendLine("{")
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 새로운 {info.IdTypeName}Comparer를 생성합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public {info.IdTypeName}Comparer() : base(")
            .AppendLine("        (id1, id2) => id1.Value == id2.Value,")
            .AppendLine("        id => id.Value.GetHashCode())")
            .AppendLine("    { }")
            .AppendLine("}")
            .AppendLine();
    }

    private static void GenerateEntityIdConverter(StringBuilder sb, EntityIdInfo info)
    {
        sb.AppendLine($"/// <summary>")
            .AppendLine($"/// EF Core ValueConverter for {info.IdTypeName}.")
            .AppendLine($"/// 데이터베이스 저장 시 string으로 변환됩니다.")
            .AppendLine($"/// </summary>")
            .AppendLine($"public sealed class {info.IdTypeName}Converter : global::Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{info.IdTypeName}, string>")
            .AppendLine("{")
            .AppendLine($"    /// <summary>")
            .AppendLine($"    /// 새로운 {info.IdTypeName}Converter를 생성합니다.")
            .AppendLine($"    /// </summary>")
            .AppendLine($"    public {info.IdTypeName}Converter() : base(")
            .AppendLine("        id => id.Value.ToString(),")
            .AppendLine($"        str => {info.IdTypeName}.Create(str))")
            .AppendLine("    { }")
            .AppendLine("}")
            .AppendLine();
    }
}
