using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ForAttribute.Generator;

[Generator]
public class AutoDescribeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the marker attribute
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoDescribeAttribute.g.cs", """
                // <auto-generated/>
                namespace ForAttribute.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoDescribeAttribute : System.Attribute { }
                """);
        });

        // ForAttributeWithMetadataName: efficient attribute-based filtering
        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ForAttribute.Generated.AutoDescribeAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var name = symbol.Name;
                    var ns = symbol.ContainingNamespace.ToDisplayString();
                    var props = symbol.GetMembers()
                        .OfType<IPropertySymbol>()
                        .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                        .Select(p => p.Name)
                        .ToArray();
                    return (Name: name, Namespace: ns, Properties: props);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, info) =>
        {
            var propList = string.Join(", ", info.Properties);
            ctx.AddSource($"{info.Name}_Describe.g.cs", $$"""
                // <auto-generated/>
                namespace {{info.Namespace}};

                public partial class {{info.Name}}
                {
                    public string Describe()
                        => "{{info.Name}} with properties: [{{propList}}]";
                }
                """);
        });
    }
}
