using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EfCoreValueConverter.Generator;

[Generator]
public class ValueConverterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("GenerateConverterAttribute.g.cs", """
                // <auto-generated/>
                namespace EfCoreValueConverter.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class GenerateConverterAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "EfCoreValueConverter.Generated.GenerateConverterAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var valueProperty = symbol.GetMembers()
                        .OfType<IPropertySymbol>()
                        .FirstOrDefault(p => p.Name == "Value");
                    var valueType = valueProperty?.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "string";
                    return (symbol.Name, Ns: symbol.ContainingNamespace.ToDisplayString(), ValueType: valueType);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            ctx.AddSource($"{data.Name}Converter.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Ns}};

                /// <summary>
                /// EF Core ValueConverter pattern for {{data.Name}}.
                /// In a real project, this would inherit from ValueConverter&lt;{{data.Name}}, {{data.ValueType}}&gt;.
                /// </summary>
                public class {{data.Name}}Converter
                {
                    public {{data.ValueType}} ConvertToProvider({{data.Name}} model)
                        => model.Value;

                    public {{data.Name}} ConvertFromProvider({{data.ValueType}} value)
                        => {{data.Name}}.From(value);
                }
                """);
        });
    }
}
