using System.Diagnostics;
using Microsoft.CodeAnalysis;

namespace DebuggingSetup.Generator;

[Generator]
public class DebuggingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Uncomment to attach debugger when generator runs:
        // if (!Debugger.IsAttached) Debugger.Launch();

        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("DebugInfo.g.cs", """
                // <auto-generated/>
                namespace DebuggingSetup.Generated;

                public static class DebugInfo
                {
                    /// <summary>Compile-time generated debug information.</summary>
                    public static string GeneratorVersion => "1.0.0";

                    /// <summary>Whether the generator was built in debug mode.</summary>
                    public static bool IsDebugBuild =>
                #if DEBUG
                        true;
                #else
                        false;
                #endif
                }
                """);
        });
    }
}
