using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TemplateDesign.Generator;

[Generator]
public class TemplateDesignGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoToStringAttribute.g.cs", """
                // <auto-generated/>
                namespace TemplateDesign.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoToStringAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "TemplateDesign.Generated.AutoToStringAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    return new ModelData(
                        symbol.Name,
                        symbol.ContainingNamespace.ToDisplayString(),
                        symbol.GetMembers()
                            .OfType<IPropertySymbol>()
                            .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                            .Select(p => p.Name)
                            .ToArray());
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var source = GenerateSource(data);
            ctx.AddSource($"{data.Name}_ToString.g.cs", source);
        });
    }

    // Template: Header → Namespace → Class → Members
    private static string GenerateSource(ModelData data)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {data.Namespace};");
        sb.AppendLine();

        // Class
        sb.AppendLine($"public partial class {data.Name}");
        sb.AppendLine("{");

        // Members
        sb.AppendLine("    public override string ToString()");
        sb.AppendLine("    {");
        sb.Append("        return $\"");
        sb.Append(data.Name);
        sb.Append(" {{ ");
        sb.Append(string.Join(", ", data.Properties.Select(p => $"{p} = {{{p}}}")));
        sb.AppendLine(" }}\";");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed record ModelData(string Name, string Namespace, string[] Properties);
}
