using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ProviderPattern.Generator;

[Generator]
public class ProviderPatternGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // IncrementalValuesProvider: produces a sequence of values
        IncrementalValuesProvider<string> classNames = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ((ClassDeclarationSyntax)ctx.Node).Identifier.Text)
            // Select: transform each value
            // Where: filter values
            .Where(static name => !name.StartsWith("_"));

        // Collect: aggregate all values into a single ImmutableArray
        IncrementalValueProvider<ImmutableArray<string>> collected = classNames.Collect();

        // RegisterSourceOutput with collected values
        context.RegisterSourceOutput(collected, static (ctx, classes) =>
        {
            var list = string.Join(",\n            ", classes.Select(c => $"\"{c}\""));
            ctx.AddSource("ClassList.g.cs", $$"""
                // <auto-generated/>
                namespace ProviderPattern.Generated;

                public static class ClassList
                {
                    public static string[] All => [
                        {{list}}
                    ];
                }
                """);
        });
    }
}
