using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DeterministicOutput.Generator;

/// <summary>
/// Demonstrates deterministic output: sorted members ensure consistent generation.
/// </summary>
[Generator]
public class DeterministicGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("RegisterAttribute.g.cs", """
                // <auto-generated/>
                namespace DeterministicOutput.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class RegisterAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "DeterministicOutput.Generated.RegisterAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    return symbol.ToDisplayString();
                })
            .Collect();

        context.RegisterSourceOutput(pipeline, static (ctx, types) =>
        {
            // Sort for deterministic output — critical for incremental caching
            var sorted = types.Sort(StringComparer.Ordinal);
            var entries = string.Join(",\n        ",
                sorted.Select(t => $"\"{t}\""));

            ctx.AddSource("ServiceRegistry.g.cs", $$"""
                // <auto-generated/>
                namespace DeterministicOutput.Generated;

                public static class ServiceRegistry
                {
                    public static string[] RegisteredTypes => [
                        {{entries}}
                    ];
                }
                """);
        });
    }
}
