using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CustomGeneratorTemplate.Generator;

[Generator]
public class CustomTemplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoMapperAttribute.g.cs", """
                // <auto-generated/>
                namespace CustomGeneratorTemplate.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoMapperAttribute(System.Type targetType) : System.Attribute
                {
                    public System.Type TargetType { get; } = targetType;
                }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "CustomGeneratorTemplate.Generated.AutoMapperAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var attr = symbol.GetAttributes()
                        .First(a => a.AttributeClass?.Name == "AutoMapperAttribute");
                    var targetType = (INamedTypeSymbol)attr.ConstructorArguments[0].Value!;
                    var sourceProps = symbol.GetMembers().OfType<IPropertySymbol>()
                        .Where(p => p.DeclaredAccessibility == Accessibility.Public)
                        .Select(p => p.Name).ToArray();
                    var targetProps = targetType.GetMembers().OfType<IPropertySymbol>()
                        .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.SetMethod is not null)
                        .Select(p => p.Name).ToArray();
                    var commonProps = sourceProps.Intersect(targetProps).OrderBy(p => p).ToArray();
                    return new MapData(
                        symbol.Name,
                        symbol.ContainingNamespace.ToDisplayString(),
                        targetType.Name,
                        targetType.ContainingNamespace.ToDisplayString(),
                        commonProps);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"namespace {data.SourceNamespace};");
            sb.AppendLine();
            sb.AppendLine($"public partial class {data.SourceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public {data.TargetNamespace}.{data.TargetName} MapTo{data.TargetName}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new {data.TargetNamespace}.{data.TargetName}");
            sb.AppendLine("        {");
            foreach (var prop in data.CommonProperties)
            {
                sb.AppendLine($"            {prop} = this.{prop},");
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            ctx.AddSource($"{data.SourceName}_MapTo{data.TargetName}.g.cs", sb.ToString());
        });
    }

    private sealed record MapData(
        string SourceName, string SourceNamespace,
        string TargetName, string TargetNamespace,
        string[] CommonProperties);
}
