using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace NamespaceHandling.Generator;

[Generator]
public class NamespaceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("GenerateMetadataAttribute.g.cs", """
                // <auto-generated/>
                namespace NamespaceHandling.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class GenerateMetadataAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "NamespaceHandling.Generated.GenerateMetadataAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var fullNamespace = symbol.ContainingNamespace.ToDisplayString();
                    return new TypeData(
                        symbol.Name,
                        fullNamespace,
                        GetNamespaceSuffix(fullNamespace));
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            ctx.AddSource($"{data.Name}_Metadata.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Namespace}};

                public partial class {{data.Name}}
                {
                    public static string FullNamespace => "{{data.Namespace}}";
                    public static string NamespaceSuffix => "{{data.NamespaceSuffix}}";
                }
                """);
        });
    }

    private static string GetNamespaceSuffix(string fullNamespace)
    {
        var parts = fullNamespace.Split('.');
        return parts.Length > 1 ? parts[parts.Length - 1] : fullNamespace;
    }

    private sealed record TypeData(string Name, string Namespace, string NamespaceSuffix);
}
