//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by PublicApiGenerator.
//     Assembly: Functorium.Adapters
//     Generated at: 2026-04-19 오후 11:53:20
// </auto-generated>
//------------------------------------------------------------------------------

namespace Functorium.Adapters.Abstractions.Errors.DestructuringPolicies.ErrorTypes
{
    public class ErrorCodeExceptionalDestructurer : Functorium.Adapters.Abstractions.Errors.DestructuringPolicies.IErrorDestructurer
    {
        public ErrorCodeExceptionalDestructurer() { }
        public bool CanHandle(LanguageExt.Common.Error error) { }
        public Serilog.Events.LogEventPropertyValue Destructure(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory factory) { }
    }
    public class ErrorCodeExpectedDestructurer : Functorium.Adapters.Abstractions.Errors.DestructuringPolicies.IErrorDestructurer
    {
        public ErrorCodeExpectedDestructurer() { }
        public bool CanHandle(LanguageExt.Common.Error error) { }
        public Serilog.Events.LogEventPropertyValue Destructure(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory factory) { }
    }
    public class ErrorCodeExpectedTDestructurer : Functorium.Adapters.Abstractions.Errors.DestructuringPolicies.IErrorDestructurer
    {
        public ErrorCodeExpectedTDestructurer() { }
        public bool CanHandle(LanguageExt.Common.Error error) { }
        public Serilog.Events.LogEventPropertyValue Destructure(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory factory) { }
    }
    public class ExceptionalDestructurer : Functorium.Adapters.Abstractions.Errors.DestructuringPolicies.IErrorDestructurer
    {
        public ExceptionalDestructurer() { }
        public bool CanHandle(LanguageExt.Common.Error error) { }
        public Serilog.Events.LogEventPropertyValue Destructure(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory factory) { }
    }
    public class ExpectedDestructurer : Functorium.Adapters.Abstractions.Errors.DestructuringPolicies.IErrorDestructurer
    {
        public ExpectedDestructurer() { }
        public bool CanHandle(LanguageExt.Common.Error error) { }
        public Serilog.Events.LogEventPropertyValue Destructure(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory factory) { }
    }
    public class ManyErrorsDestructurer : Functorium.Adapters.Abstractions.Errors.DestructuringPolicies.IErrorDestructurer
    {
        public ManyErrorsDestructurer() { }
        public bool CanHandle(LanguageExt.Common.Error error) { }
        public Serilog.Events.LogEventPropertyValue Destructure(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory factory) { }
    }
}
namespace Functorium.Adapters.Abstractions.Errors.DestructuringPolicies
{
    public class ErrorsDestructuringPolicy : Serilog.Core.IDestructuringPolicy
    {
        public ErrorsDestructuringPolicy() { }
        public bool TryDestructure(object value, Serilog.Core.ILogEventPropertyValueFactory propertyValueFactory, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out Serilog.Events.LogEventPropertyValue? result) { }
        public static Serilog.Events.LogEventPropertyValue DestructureError(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory propertyValueFactory) { }
    }
    public interface IErrorDestructurer
    {
        bool CanHandle(LanguageExt.Common.Error error);
        Serilog.Events.LogEventPropertyValue Destructure(LanguageExt.Common.Error error, Serilog.Core.ILogEventPropertyValueFactory factory);
    }
}
namespace Functorium.Adapters.Abstractions.Options
{
    public static class OptionsConfigurator
    {
        public static Microsoft.Extensions.Options.OptionsBuilder<TOptions> RegisterConfigureOptions<TOptions, TValidator>(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, string configurationSectionName)
            where TOptions :  class
            where TValidator :  class, FluentValidation.IValidator<TOptions> { }
    }
}
namespace Functorium.Adapters.Abstractions.Registrations
{
    public static class DomainEventRegistration
    {
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection RegisterDomainEventHandlersFromAssembly(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, System.Reflection.Assembly assembly, Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime = 1) { }
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection RegisterDomainEventPublisher(this Microsoft.Extensions.DependencyInjection.IServiceCollection services) { }
    }
    public static class OpenTelemetryRegistration
    {
        public static Functorium.Adapters.Observabilities.Builders.OpenTelemetryBuilder RegisterOpenTelemetry(this Microsoft.Extensions.DependencyInjection.IServiceCollection services, Microsoft.Extensions.Configuration.IConfiguration configuration, System.Reflection.Assembly projectAssembly) { }
    }
}
namespace Functorium.Adapters.Errors
{
    public static class AdapterError
    {
        public static LanguageExt.Common.Error For(System.Type adapterType, Functorium.Adapters.Errors.AdapterErrorType errorType, string currentValue, string message) { }
        public static LanguageExt.Common.Error For<TAdapter>(Functorium.Adapters.Errors.AdapterErrorType errorType, string currentValue, string message) { }
        public static LanguageExt.Common.Error For<TAdapter, TValue>(Functorium.Adapters.Errors.AdapterErrorType errorType, TValue currentValue, string message)
            where TValue :  notnull { }
        public static LanguageExt.Common.Error For<TAdapter, T1, T2>(Functorium.Adapters.Errors.AdapterErrorType errorType, T1 value1, T2 value2, string message)
            where T1 :  notnull
            where T2 :  notnull { }
        public static LanguageExt.Common.Error For<TAdapter, T1, T2, T3>(Functorium.Adapters.Errors.AdapterErrorType errorType, T1 value1, T2 value2, T3 value3, string message)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static LanguageExt.Common.Error FromException<TAdapter>(Functorium.Adapters.Errors.AdapterErrorType errorType, System.Exception exception) { }
    }
    public abstract class AdapterErrorType : Functorium.Abstractions.Errors.ErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType>
    {
        protected AdapterErrorType() { }
        public sealed class AlreadyExists : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.AlreadyExists>
        {
            public AlreadyExists() { }
        }
        public sealed class ConnectionFailed : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.ConnectionFailed>
        {
            public ConnectionFailed(string? Target = null) { }
            public string? Target { get; init; }
        }
        public abstract class Custom : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Custom>
        {
            protected Custom() { }
        }
        public sealed class DataCorruption : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.DataCorruption>
        {
            public DataCorruption() { }
        }
        public sealed class Deserialization : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Deserialization>
        {
            public Deserialization(string? Format = null) { }
            public string? Format { get; init; }
        }
        public sealed class Duplicate : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Duplicate>
        {
            public Duplicate() { }
        }
        public sealed class Empty : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Empty>
        {
            public Empty() { }
        }
        public sealed class ExternalServiceUnavailable : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.ExternalServiceUnavailable>
        {
            public ExternalServiceUnavailable(string? ServiceName = null) { }
            public string? ServiceName { get; init; }
        }
        public sealed class Forbidden : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Forbidden>
        {
            public Forbidden() { }
        }
        public sealed class HandlerFailed : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.HandlerFailed>
        {
            public HandlerFailed() { }
        }
        public sealed class InvalidEventType : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.InvalidEventType>
        {
            public InvalidEventType() { }
        }
        public sealed class InvalidState : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.InvalidState>
        {
            public InvalidState() { }
        }
        public sealed class NotConfigured : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.NotConfigured>
        {
            public NotConfigured() { }
        }
        public sealed class NotFound : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.NotFound>
        {
            public NotFound() { }
        }
        public sealed class NotSupported : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.NotSupported>
        {
            public NotSupported() { }
        }
        public sealed class Null : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Null>
        {
            public Null() { }
        }
        public sealed class PartialNotFound : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.PartialNotFound>
        {
            public PartialNotFound() { }
        }
        public sealed class PipelineException : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.PipelineException>
        {
            public PipelineException() { }
        }
        public sealed class PipelineValidation : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.PipelineValidation>
        {
            public PipelineValidation(string? PropertyName = null) { }
            public string? PropertyName { get; init; }
        }
        public sealed class PublishCancelled : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.PublishCancelled>
        {
            public PublishCancelled() { }
        }
        public sealed class PublishFailed : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.PublishFailed>
        {
            public PublishFailed() { }
        }
        public sealed class Serialization : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Serialization>
        {
            public Serialization(string? Format = null) { }
            public string? Format { get; init; }
        }
        public sealed class Timeout : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Timeout>
        {
            public Timeout(System.TimeSpan? Duration = default) { }
            public System.TimeSpan? Duration { get; init; }
        }
        public sealed class Unauthorized : Functorium.Adapters.Errors.AdapterErrorType, System.IEquatable<Functorium.Adapters.Errors.AdapterErrorType.Unauthorized>
        {
            public Unauthorized() { }
        }
    }
}
namespace Functorium.Adapters.Events
{
    public static class DomainEventHandlerLoggerExtensions
    {
        public static void LogDomainEventHandlerRequest<TEvent>(this Microsoft.Extensions.Logging.ILogger logger, string handlerName, TEvent domainEvent)
            where TEvent : Functorium.Domains.Events.IDomainEvent { }
        public static void LogDomainEventHandlerResponseError(this Microsoft.Extensions.Logging.ILogger logger, string handlerName, string eventTypeName, string eventId, double elapsed, string errorType, string errorCode, LanguageExt.Common.Error error) { }
        public static void LogDomainEventHandlerResponseError(this Microsoft.Extensions.Logging.ILogger logger, string handlerName, string eventTypeName, string eventId, double elapsed, string errorType, string errorCode, System.Exception exception) { }
        public static void LogDomainEventHandlerResponseSuccess(this Microsoft.Extensions.Logging.ILogger logger, string handlerName, string eventTypeName, string eventId, double elapsed) { }
        public static void LogDomainEventHandlerResponseWarning(this Microsoft.Extensions.Logging.ILogger logger, string handlerName, string eventTypeName, string eventId, double elapsed, string errorType, string errorCode, LanguageExt.Common.Error error) { }
    }
    public sealed class DomainEventPublisher : Functorium.Applications.Events.IDomainEventPublisher
    {
        public DomainEventPublisher(Mediator.IPublisher publisher, Functorium.Applications.Events.IDomainEventCollector collector) { }
        public LanguageExt.FinT<LanguageExt.IO, LanguageExt.Unit> Publish<TEvent>(TEvent domainEvent, System.Threading.CancellationToken cancellationToken = default)
            where TEvent : Functorium.Domains.Events.IDomainEvent { }
        public LanguageExt.FinT<LanguageExt.IO, LanguageExt.Seq<Functorium.Applications.Events.PublishResult>> PublishTrackedEvents(System.Threading.CancellationToken cancellationToken = default) { }
    }
    public static class DomainEventPublisherLoggerExtensions
    {
        public static void LogDomainEventPublisherRequest<TEvent>(this Microsoft.Extensions.Logging.ILogger logger, TEvent domainEvent)
            where TEvent : Functorium.Domains.Events.IDomainEvent { }
        public static void LogDomainEventPublisherResponseError<TEvent>(this Microsoft.Extensions.Logging.ILogger logger, TEvent domainEvent, double elapsed, string errorType, string errorCode, LanguageExt.Common.Error error)
            where TEvent : Functorium.Domains.Events.IDomainEvent { }
        public static void LogDomainEventPublisherResponseSuccess<TEvent>(this Microsoft.Extensions.Logging.ILogger logger, TEvent domainEvent, double elapsed)
            where TEvent : Functorium.Domains.Events.IDomainEvent { }
        public static void LogDomainEventPublisherResponseWarning<TEvent>(this Microsoft.Extensions.Logging.ILogger logger, TEvent domainEvent, double elapsed, string errorType, string errorCode, LanguageExt.Common.Error error)
            where TEvent : Functorium.Domains.Events.IDomainEvent { }
        public static void LogDomainEventsPublisherRequest(this Microsoft.Extensions.Logging.ILogger logger, string aggregateType, string methodName, int eventCount) { }
        public static void LogDomainEventsPublisherResponseError(this Microsoft.Extensions.Logging.ILogger logger, string aggregateType, string methodName, int eventCount, double elapsed, string errorType, string errorCode, LanguageExt.Common.Error error) { }
        public static void LogDomainEventsPublisherResponsePartialFailure(this Microsoft.Extensions.Logging.ILogger logger, string aggregateType, string methodName, int eventCount, int successCount, int failureCount, double elapsed) { }
        public static void LogDomainEventsPublisherResponseSuccess(this Microsoft.Extensions.Logging.ILogger logger, string aggregateType, string methodName, int eventCount, double elapsed) { }
        public static void LogDomainEventsPublisherResponseWarning(this Microsoft.Extensions.Logging.ILogger logger, string aggregateType, string methodName, int eventCount, double elapsed, string errorType, string errorCode, LanguageExt.Common.Error error) { }
    }
    public sealed class ObservableDomainEventNotificationPublisher : Mediator.INotificationPublisher, System.IDisposable
    {
        public ObservableDomainEventNotificationPublisher(System.Diagnostics.ActivitySource activitySource, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory, System.Diagnostics.Metrics.IMeterFactory meterFactory, Microsoft.Extensions.Options.IOptions<Functorium.Adapters.Observabilities.OpenTelemetryOptions> openTelemetryOptions, System.IServiceProvider serviceProvider) { }
        public void Dispose() { }
        public System.Threading.Tasks.ValueTask Publish<TNotification>(Mediator.NotificationHandlers<TNotification> handlers, TNotification notification, System.Threading.CancellationToken cancellationToken)
            where TNotification : Mediator.INotification { }
    }
    public sealed class ObservableDomainEventPublisher : Functorium.Applications.Events.IDomainEventPublisher, System.IDisposable
    {
        public ObservableDomainEventPublisher(System.Diagnostics.ActivitySource activitySource, Functorium.Applications.Events.IDomainEventPublisher inner, Functorium.Applications.Events.IDomainEventCollector collector, Microsoft.Extensions.Logging.ILogger<Functorium.Adapters.Events.ObservableDomainEventPublisher> logger, System.Diagnostics.Metrics.IMeterFactory meterFactory, Microsoft.Extensions.Options.IOptions<Functorium.Adapters.Observabilities.OpenTelemetryOptions> openTelemetryOptions) { }
        public void Dispose() { }
        public LanguageExt.FinT<LanguageExt.IO, LanguageExt.Unit> Publish<TEvent>(TEvent domainEvent, System.Threading.CancellationToken cancellationToken = default)
            where TEvent : Functorium.Domains.Events.IDomainEvent { }
        public LanguageExt.FinT<LanguageExt.IO, LanguageExt.Seq<Functorium.Applications.Events.PublishResult>> PublishTrackedEvents(System.Threading.CancellationToken cancellationToken = default) { }
    }
}
namespace Functorium.Adapters.Observabilities.Builders.Configurators
{
    public class LoggingConfigurator
    {
        public Functorium.Adapters.Observabilities.OpenTelemetryOptions Options { get; }
        public Functorium.Adapters.Observabilities.Builders.Configurators.LoggingConfigurator AddDestructuringPolicy<TPolicy>()
            where TPolicy : Serilog.Core.IDestructuringPolicy, new () { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.LoggingConfigurator AddEnricher(Serilog.Core.ILogEventEnricher enricher) { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.LoggingConfigurator AddEnricher<TEnricher>()
            where TEnricher : Serilog.Core.ILogEventEnricher, new () { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.LoggingConfigurator Configure(System.Action<Serilog.LoggerConfiguration> configure) { }
    }
    public class MetricsConfigurator
    {
        public Functorium.Adapters.Observabilities.OpenTelemetryOptions Options { get; }
        public Functorium.Adapters.Observabilities.Builders.Configurators.MetricsConfigurator AddInstrumentation(System.Action<OpenTelemetry.Metrics.MeterProviderBuilder> configure) { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.MetricsConfigurator AddMeter(string meterName) { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.MetricsConfigurator Configure(System.Action<OpenTelemetry.Metrics.MeterProviderBuilder> configure) { }
    }
    public class PipelineConfigurator
    {
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator AddCustomPipeline<TPipeline>()
            where TPipeline :  class { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseCaching() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseCtxEnricher() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseException() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseLogging() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseMetrics() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseObservability() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseTracing() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseTransaction() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator UseValidation() { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator WithLifetime(Microsoft.Extensions.DependencyInjection.ServiceLifetime lifetime) { }
    }
    public class TracingConfigurator
    {
        public Functorium.Adapters.Observabilities.OpenTelemetryOptions Options { get; }
        public Functorium.Adapters.Observabilities.Builders.Configurators.TracingConfigurator AddProcessor(OpenTelemetry.BaseProcessor<System.Diagnostics.Activity> processor) { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.TracingConfigurator AddSource(string sourceName) { }
        public Functorium.Adapters.Observabilities.Builders.Configurators.TracingConfigurator Configure(System.Action<OpenTelemetry.Trace.TracerProviderBuilder> configure) { }
    }
}
namespace Functorium.Adapters.Observabilities.Builders
{
    public class OpenTelemetryBuilder
    {
        public Microsoft.Extensions.DependencyInjection.IServiceCollection Build() { }
        public Functorium.Adapters.Observabilities.Builders.OpenTelemetryBuilder ConfigureLogging(System.Action<Functorium.Adapters.Observabilities.Builders.Configurators.LoggingConfigurator> configure) { }
        public Functorium.Adapters.Observabilities.Builders.OpenTelemetryBuilder ConfigureMetrics(System.Action<Functorium.Adapters.Observabilities.Builders.Configurators.MetricsConfigurator> configure) { }
        public Functorium.Adapters.Observabilities.Builders.OpenTelemetryBuilder ConfigurePipelines(System.Action<Functorium.Adapters.Observabilities.Builders.Configurators.PipelineConfigurator> configure) { }
        public Functorium.Adapters.Observabilities.Builders.OpenTelemetryBuilder ConfigureStartupLogger(System.Action<Microsoft.Extensions.Logging.ILogger> configure) { }
        public Functorium.Adapters.Observabilities.Builders.OpenTelemetryBuilder ConfigureTracing(System.Action<Functorium.Adapters.Observabilities.Builders.Configurators.TracingConfigurator> configure) { }
        public Functorium.Adapters.Observabilities.OpenTelemetryOptions GetOptions(System.IServiceProvider serviceProvider) { }
        public Functorium.Adapters.Observabilities.Builders.OpenTelemetryBuilder WithAdapterObservability(bool enable = true) { }
        public static System.Collections.Generic.Dictionary<string, object> CreateResourceAttributes(Functorium.Adapters.Observabilities.OpenTelemetryOptions options) { }
        public static OpenTelemetry.Exporter.OtlpExportProtocol ToOtlpProtocolForExporter(Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol protocol) { }
        public static Serilog.Sinks.OpenTelemetry.OtlpProtocol ToOtlpProtocolForSerilog(Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol protocol) { }
    }
}
namespace Functorium.Adapters.Observabilities.Contexts
{
    public static class MetricsTagContext
    {
        public static System.Collections.Generic.IReadOnlyList<System.Collections.Generic.KeyValuePair<string, object?>>? CurrentTags { get; }
        public static bool HasTags { get; }
        public static System.IDisposable Push(string name, object? value) { }
    }
}
namespace Functorium.Adapters.Observabilities
{
    public static class ElapsedTimeCalculator
    {
        public static double CalculateElapsedSeconds(long startTimestamp) { }
        public static long GetCurrentTimestamp() { }
        public sealed class Timer : System.IDisposable
        {
            public Timer() { }
            public double ElapsedSeconds { get; }
            public void Dispose() { }
        }
    }
    public static class ErrorInfoExtractor
    {
        [return: System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "ErrorType",
                "ErrorCode"})]
        public static System.ValueTuple<string, string> GetErrorInfo(LanguageExt.Common.Error error) { }
        [return: System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "ErrorType",
                "ErrorCode"})]
        public static System.ValueTuple<string, string> GetErrorInfo(System.Exception exception) { }
    }
    public interface IOpenTelemetryOptions
    {
        bool EnablePrometheusExporter { get; }
        string ServiceNamespace { get; }
    }
    public sealed class ObservableSignalScope : System.IDisposable
    {
        public void Dispose() { }
        public static Functorium.Adapters.Observabilities.ObservableSignalScope Begin(Microsoft.Extensions.Logging.ILogger logger, string layer, string category, string handler, string method) { }
    }
    public sealed class OpenTelemetryOptions : Functorium.Adapters.Observabilities.IOpenTelemetryOptions, Functorium.Adapters.Observabilities.Loggers.IStartupOptionsLogger
    {
        public const string SectionName = "OpenTelemetry";
        public OpenTelemetryOptions() { }
        public string CollectorEndpoint { get; set; }
        public string CollectorProtocol { get; set; }
        public bool EnablePrometheusExporter { get; set; }
        public string? LoggingEndpoint { get; set; }
        public string? LoggingProtocol { get; set; }
        public string? MetricsEndpoint { get; set; }
        public string? MetricsProtocol { get; set; }
        public double SamplingRate { get; set; }
        public string ServiceInstanceId { get; }
        public string ServiceName { get; set; }
        public string ServiceNamespace { get; set; }
        public string ServiceVersion { get; }
        public string? TracingEndpoint { get; set; }
        public string? TracingProtocol { get; set; }
        public string GetLoggingEndpoint() { }
        public Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol GetLoggingProtocol() { }
        public string GetMetricsEndpoint() { }
        public Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol GetMetricsProtocol() { }
        public string GetTracingEndpoint() { }
        public Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol GetTracingProtocol() { }
        public void LogConfiguration(Microsoft.Extensions.Logging.ILogger logger) { }
        public sealed class OtlpCollectorProtocol : Ardalis.SmartEnum.SmartEnum<Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol>
        {
            public static readonly Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol Grpc;
            public static readonly Functorium.Adapters.Observabilities.OpenTelemetryOptions.OtlpCollectorProtocol HttpProtobuf;
        }
        public sealed class Validator : FluentValidation.AbstractValidator<Functorium.Adapters.Observabilities.OpenTelemetryOptions>
        {
            public Validator() { }
        }
    }
}
namespace Functorium.Adapters.Observabilities.Formatters
{
    public sealed class OpenSearchJsonFormatter : Serilog.Formatting.ITextFormatter
    {
        public OpenSearchJsonFormatter() { }
        public void Format(Serilog.Events.LogEvent logEvent, System.IO.TextWriter output) { }
    }
}
namespace Functorium.Adapters.Observabilities.Loggers
{
    public interface IStartupOptionsLogger
    {
        void LogConfiguration(Microsoft.Extensions.Logging.ILogger logger);
    }
    public class StartupLogger : Microsoft.Extensions.Hosting.IHostedService
    {
        public StartupLogger(Microsoft.Extensions.Logging.ILogger<Functorium.Adapters.Observabilities.Loggers.StartupLogger> logger, Microsoft.Extensions.Hosting.IHostEnvironment environment, System.Collections.Generic.IEnumerable<Functorium.Adapters.Observabilities.Loggers.IStartupOptionsLogger> optionsLoggers, System.Action<Microsoft.Extensions.Logging.ILogger>? additionalLogger = null) { }
        public System.Threading.Tasks.Task StartAsync(System.Threading.CancellationToken cancellationToken) { }
        public System.Threading.Tasks.Task StopAsync(System.Threading.CancellationToken cancellationToken) { }
    }
}
namespace Functorium.Adapters.Observabilities.Naming
{
    public static class ObservabilityNaming
    {
        public static class Categories
        {
            public const string Event = "event";
            public const string Repository = "repository";
            public const string Unknown = "unknown";
            public const string Usecase = "usecase";
        }
        public static class CategoryTypes
        {
            public const string Command = "command";
            public const string Event = "event";
            public const string Query = "query";
            public const string Unknown = "unknown";
        }
        public static class CustomAttributes
        {
            public const string ErrorCode = "error.code";
            public const string RequestAggregateCount = "request.aggregate.count";
            public const string RequestCategoryName = "request.category.name";
            public const string RequestCategoryType = "request.category.type";
            public const string RequestEventCount = "request.event.count";
            public const string RequestEventId = "request.event.id";
            public const string RequestEventType = "request.event.type";
            public const string RequestHandlerMethod = "request.handler.method";
            public const string RequestHandlerName = "request.handler.name";
            public const string RequestLayer = "request.layer";
            public const string RequestMessage = "request.message";
            public const string RequestParams = "request.params";
            public const string ResponseElapsed = "response.elapsed";
            public const string ResponseEventFailureCount = "response.event.failure_count";
            public const string ResponseEventSuccessCount = "response.event.success_count";
            public const string ResponseMessage = "response.message";
            public const string ResponseStatus = "response.status";
        }
        public static class ErrorTypes
        {
            public const string Aggregate = "aggregate";
            public const string Exceptional = "exceptional";
            public const string Expected = "expected";
        }
        public static class EventIds
        {
            public static class Adapter
            {
                public static readonly Microsoft.Extensions.Logging.EventId AdapterRequest;
                public static readonly Microsoft.Extensions.Logging.EventId AdapterResponseError;
                public static readonly Microsoft.Extensions.Logging.EventId AdapterResponseSuccess;
                public static readonly Microsoft.Extensions.Logging.EventId AdapterResponseWarning;
                public static readonly Microsoft.Extensions.Logging.EventId ObservableSignalDebug;
                public static readonly Microsoft.Extensions.Logging.EventId ObservableSignalError;
                public static readonly Microsoft.Extensions.Logging.EventId ObservableSignalWarning;
            }
            public static class Application
            {
                public static readonly Microsoft.Extensions.Logging.EventId ApplicationRequest;
                public static readonly Microsoft.Extensions.Logging.EventId ApplicationResponseError;
                public static readonly Microsoft.Extensions.Logging.EventId ApplicationResponseSuccess;
                public static readonly Microsoft.Extensions.Logging.EventId ApplicationResponseWarning;
            }
        }
        public static class Layers
        {
            public const string Adapter = "adapter";
            public const string Application = "application";
        }
        public static class Methods
        {
            public const string Handle = "Handle";
            public const string Publish = "Publish";
            public const string PublishTrackedEvents = "PublishTrackedEvents";
        }
        public static class Metrics
        {
            public static string AdapterDuration(string category) { }
            public static string AdapterRequest(string category) { }
            public static string AdapterResponse(string category) { }
            public static string Duration(string layer, string category) { }
            public static string Requests(string layer, string category) { }
            public static string Responses(string layer, string category) { }
            public static string UsecaseDuration(string categoryType) { }
            public static string UsecaseRequest(string categoryType) { }
            public static string UsecaseResponse(string categoryType) { }
        }
        public static class OTelAttributes
        {
            public const string DeploymentEnvironment = "deployment.environment";
            public const string ErrorType = "error.type";
            public const string ServiceInstanceId = "service.instance.id";
            public const string ServiceName = "service.name";
            public const string ServiceNamespace = "service.namespace";
            public const string ServiceVersion = "service.version";
        }
        public static class Spans
        {
            public static string OperationName(string layer, string category, string handler, string method) { }
        }
        public static class Status
        {
            public const string Failure = "failure";
            public const string Success = "success";
        }
    }
}
namespace Functorium.Adapters.Pipelines
{
    public interface ICustomUsecasePipeline { }
    public static class UsecaseLoggerExtensions
    {
        public static void LogUsecaseRequest<T>(this Microsoft.Extensions.Logging.ILogger logger, string requestLayer, string requestCategory, string requestCategoryType, string requestHandler, string requestHandlerMethod, T? request) { }
        public static void LogUsecaseResponseError(this Microsoft.Extensions.Logging.ILogger logger, string requestLayer, string requestCategory, string requestCategoryType, string requestHandler, string requestHandlerMethod, string responseStatus, double responseElapsed, string errorType, string errorCode, LanguageExt.Common.Error error) { }
        public static void LogUsecaseResponseSuccess<T>(this Microsoft.Extensions.Logging.ILogger logger, string requestLayer, string requestCategory, string requestCategoryType, string requestHandler, string requestHandlerMethod, T? response, string responseStatus, double responseElapsed) { }
        public static void LogUsecaseResponseWarning(this Microsoft.Extensions.Logging.ILogger logger, string requestLayer, string requestCategory, string requestCategoryType, string requestHandler, string requestHandlerMethod, string responseStatus, double responseElapsed, string errorType, string errorCode, LanguageExt.Common.Error error) { }
    }
    public abstract class UsecaseMetricCustomPipelineBase<TRequest> : Functorium.Adapters.Pipelines.UsecasePipelineBase<TRequest>, Functorium.Adapters.Pipelines.ICustomUsecasePipeline
    {
        protected const string CountUnit = "requests";
        protected const string DurationUnit = "s";
        protected readonly System.Diagnostics.Metrics.Meter _meter;
        protected UsecaseMetricCustomPipelineBase(string serviceNamespace, System.Diagnostics.Metrics.IMeterFactory meterFactory) { }
        protected string GetMetricName(string metricName) { }
        protected string GetMetricNameWithoutHandler(string metricName) { }
        public class RequestDuration : System.IDisposable
        {
            public RequestDuration(System.Diagnostics.Metrics.Histogram<double> histogram) { }
            public void Dispose() { }
        }
    }
    public abstract class UsecasePipelineBase<TRequest>
    {
        protected UsecasePipelineBase() { }
        [return: System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "ErrorType",
                "ErrorCode"})]
        protected static System.ValueTuple<string, string> GetErrorInfo(LanguageExt.Common.Error error) { }
        protected static string GetRequestCategoryType(System.Type requestType) { }
        protected static string GetRequestCategoryType<T>(T request) { }
        protected static string GetRequestHandler() { }
        protected static string GetRequestHandlerLower() { }
        protected static string GetRequestHandlerPath() { }
    }
    public abstract class UsecaseTracingCustomPipelineBase<TRequest> : Functorium.Adapters.Pipelines.UsecasePipelineBase<TRequest>, Functorium.Adapters.Pipelines.ICustomUsecasePipeline
    {
        protected readonly System.Diagnostics.ActivitySource _activitySource;
        protected UsecaseTracingCustomPipelineBase(System.Diagnostics.ActivitySource activitySource) { }
        protected string GetActivityName(string operationName) { }
        protected System.Diagnostics.Activity? StartCustomActivity(string operationName, System.Diagnostics.ActivityKind kind = 0) { }
        protected static void SetStandardRequestTags(System.Diagnostics.Activity activity, string method) { }
    }
}
namespace Functorium.Adapters.Repositories
{
    public abstract class DapperQueryBase<TEntity, TDto>
    {
        protected DapperQueryBase(System.Data.IDbConnection connection) { }
        protected DapperQueryBase(System.Data.IDbConnection connection, Functorium.Adapters.Repositories.DapperSpecTranslator<TEntity> translator, string tableAlias = "") { }
        protected abstract System.Collections.Generic.Dictionary<string, string> AllowedSortColumns { get; }
        protected abstract string CountSql { get; }
        protected virtual string CursorPaginationClause { get; }
        protected abstract string DefaultOrderBy { get; }
        protected virtual string PaginationClause { get; }
        protected abstract string SelectSql { get; }
        [return: System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "Where",
                "Params"})]
        protected virtual System.ValueTuple<string, Dapper.DynamicParameters> BuildWhereClause(Functorium.Domains.Specifications.Specification<TEntity> spec) { }
        protected virtual string? GetCursorValue(TDto item, string fieldName) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, Functorium.Applications.Queries.PagedResult<TDto>> Search(Functorium.Domains.Specifications.Specification<TEntity> spec, Functorium.Applications.Queries.PageRequest page, Functorium.Applications.Queries.SortExpression sort) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, Functorium.Applications.Queries.CursorPagedResult<TDto>> SearchByCursor(Functorium.Domains.Specifications.Specification<TEntity> spec, Functorium.Applications.Queries.CursorPageRequest cursor, Functorium.Applications.Queries.SortExpression sort) { }
        [System.Runtime.CompilerServices.AsyncIteratorStateMachine(typeof(Functorium.Adapters.Repositories.DapperQueryBase<TEntity, TDto>.<Stream>d__28))]
        public virtual System.Collections.Generic.IAsyncEnumerable<TDto> Stream(Functorium.Domains.Specifications.Specification<TEntity> spec, Functorium.Applications.Queries.SortExpression sort, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken cancellationToken = default) { }
        protected static Dapper.DynamicParameters Params([System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "Name",
                "Value"})] params System.ValueTuple<string, object>[] values) { }
    }
    public sealed class DapperSpecTranslator<TEntity>
    {
        public DapperSpecTranslator() { }
        [return: System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "Where",
                "Params"})]
        public System.ValueTuple<string, Dapper.DynamicParameters> Translate(Functorium.Domains.Specifications.Specification<TEntity> spec, string tableAlias = "") { }
        public Functorium.Adapters.Repositories.DapperSpecTranslator<TEntity> When<TSpec>([System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "Where",
                "Params"})] System.Func<TSpec, string, System.ValueTuple<string, Dapper.DynamicParameters>> handler)
            where TSpec : Functorium.Domains.Specifications.Specification<TEntity> { }
        public Functorium.Adapters.Repositories.DapperSpecTranslator<TEntity> WhenAll([System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "Where",
                "Params"})] System.Func<string, System.ValueTuple<string, Dapper.DynamicParameters>> handler) { }
        public static Dapper.DynamicParameters Params([System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "Name",
                "Value"})] params System.ValueTuple<string, object>[] values) { }
        public static string Prefix(string tableAlias) { }
    }
    public abstract class EfCoreRepositoryBase<TAggregate, TId, TModel> : Functorium.Abstractions.Observabilities.IObservablePort, Functorium.Domains.Repositories.IRepository<TAggregate, TId>
        where TAggregate : Functorium.Domains.Entities.AggregateRoot<TId>
        where TId :  struct, Functorium.Domains.Entities.IEntityId<TId>
        where TModel :  class, Functorium.Adapters.Repositories.IHasStringId
    {
        protected EfCoreRepositoryBase(Functorium.Applications.Events.IDomainEventCollector eventCollector, System.Func<System.Linq.IQueryable<TModel>, System.Linq.IQueryable<TModel>>? applyIncludes = null, Functorium.Domains.Specifications.Expressions.PropertyMap<TAggregate, TModel>? propertyMap = null) { }
        protected abstract Microsoft.EntityFrameworkCore.DbContext DbContext { get; }
        protected abstract Microsoft.EntityFrameworkCore.DbSet<TModel> DbSet { get; }
        protected Functorium.Applications.Events.IDomainEventCollector EventCollector { get; }
        protected virtual int IdBatchSize { get; }
        protected Functorium.Domains.Specifications.Expressions.PropertyMap<TAggregate, TModel>? PropertyMap { get; }
        public virtual string RequestCategory { get; }
        protected LanguageExt.Fin<System.Linq.IQueryable<TModel>> BuildQuery(Functorium.Domains.Specifications.Specification<TAggregate> spec) { }
        protected abstract void BuildSetters(Microsoft.EntityFrameworkCore.Query.UpdateSettersBuilder<TModel> setters, TModel model);
        protected virtual System.Linq.Expressions.Expression<System.Func<TModel, bool>> ByIdPredicate(TId id) { }
        protected virtual System.Linq.Expressions.Expression<System.Func<TModel, bool>> ByIdsPredicate(System.Collections.Generic.IReadOnlyList<TId> ids) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> Count(Functorium.Domains.Specifications.Specification<TAggregate> spec) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, TAggregate> Create(TAggregate aggregate) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> CreateRange(System.Collections.Generic.IReadOnlyList<TAggregate> aggregates) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> Delete(TId id) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> DeleteBy(Functorium.Domains.Specifications.Specification<TAggregate> spec) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> DeleteRange(System.Collections.Generic.IReadOnlyList<TId> ids) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, bool> Exists(Functorium.Domains.Specifications.Specification<TAggregate> spec) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, TAggregate> GetById(TId id) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, LanguageExt.Seq<TAggregate>> GetByIds(System.Collections.Generic.IReadOnlyList<TId> ids) { }
        protected LanguageExt.Common.Error NotConfiguredError(string message) { }
        protected LanguageExt.Common.Error NotFoundError(TId id) { }
        protected LanguageExt.Common.Error NotSupportedError(string currentValue, string message) { }
        protected LanguageExt.Common.Error PartialNotFoundError(System.Collections.Generic.IReadOnlyList<TId> requestedIds, LanguageExt.Seq<TAggregate> foundAggregates) { }
        protected System.Linq.IQueryable<TModel> ReadQuery() { }
        protected System.Linq.IQueryable<TModel> ReadQueryIgnoringFilters() { }
        protected abstract TAggregate ToDomain(TModel model);
        protected abstract TModel ToModel(TAggregate aggregate);
        public virtual LanguageExt.FinT<LanguageExt.IO, TAggregate> Update(TAggregate aggregate) { }
        protected LanguageExt.FinT<LanguageExt.IO, int> UpdateBy(Functorium.Domains.Specifications.Specification<TAggregate> spec, System.Action<Microsoft.EntityFrameworkCore.Query.UpdateSettersBuilder<TModel>> setters) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> UpdateRange(System.Collections.Generic.IReadOnlyList<TAggregate> aggregates) { }
    }
    public interface IHasStringId
    {
        string Id { get; set; }
    }
    public abstract class InMemoryQueryBase<TEntity, TDto>
    {
        protected InMemoryQueryBase() { }
        protected abstract string DefaultSortField { get; }
        protected abstract System.Collections.Generic.IEnumerable<TDto> GetProjectedItems(Functorium.Domains.Specifications.Specification<TEntity> spec);
        public virtual LanguageExt.FinT<LanguageExt.IO, Functorium.Applications.Queries.PagedResult<TDto>> Search(Functorium.Domains.Specifications.Specification<TEntity> spec, Functorium.Applications.Queries.PageRequest page, Functorium.Applications.Queries.SortExpression sort) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, Functorium.Applications.Queries.CursorPagedResult<TDto>> SearchByCursor(Functorium.Domains.Specifications.Specification<TEntity> spec, Functorium.Applications.Queries.CursorPageRequest cursor, Functorium.Applications.Queries.SortExpression sort) { }
        protected abstract System.Func<TDto, object> SortSelector(string fieldName);
        [System.Runtime.CompilerServices.AsyncIteratorStateMachine(typeof(Functorium.Adapters.Repositories.InMemoryQueryBase<TEntity, TDto>.<Stream>d__6))]
        public virtual System.Collections.Generic.IAsyncEnumerable<TDto> Stream(Functorium.Domains.Specifications.Specification<TEntity> spec, Functorium.Applications.Queries.SortExpression sort, [System.Runtime.CompilerServices.EnumeratorCancellation] System.Threading.CancellationToken cancellationToken = default) { }
    }
    public abstract class InMemoryRepositoryBase<TAggregate, TId> : Functorium.Abstractions.Observabilities.IObservablePort, Functorium.Domains.Repositories.IRepository<TAggregate, TId>
        where TAggregate : Functorium.Domains.Entities.AggregateRoot<TId>
        where TId :  struct, Functorium.Domains.Entities.IEntityId<TId>
    {
        protected InMemoryRepositoryBase(Functorium.Applications.Events.IDomainEventCollector eventCollector) { }
        protected Functorium.Applications.Events.IDomainEventCollector EventCollector { get; }
        public virtual string RequestCategory { get; }
        protected abstract System.Collections.Concurrent.ConcurrentDictionary<TId, TAggregate> Store { get; }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> Count(Functorium.Domains.Specifications.Specification<TAggregate> spec) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, TAggregate> Create(TAggregate aggregate) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> CreateRange(System.Collections.Generic.IReadOnlyList<TAggregate> aggregates) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> Delete(TId id) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> DeleteBy(Functorium.Domains.Specifications.Specification<TAggregate> spec) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> DeleteRange(System.Collections.Generic.IReadOnlyList<TId> ids) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, bool> Exists(Functorium.Domains.Specifications.Specification<TAggregate> spec) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, TAggregate> GetById(TId id) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, LanguageExt.Seq<TAggregate>> GetByIds(System.Collections.Generic.IReadOnlyList<TId> ids) { }
        protected LanguageExt.Common.Error NotFoundError(TId id) { }
        protected LanguageExt.Common.Error PartialNotFoundError(System.Collections.Generic.IReadOnlyList<TId> requestedIds, System.Collections.Generic.List<TAggregate> foundAggregates) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, TAggregate> Update(TAggregate aggregate) { }
        public virtual LanguageExt.FinT<LanguageExt.IO, int> UpdateRange(System.Collections.Generic.IReadOnlyList<TAggregate> aggregates) { }
    }
}
namespace Functorium.Adapters.SourceGenerators
{
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=false, Inherited=false)]
    public sealed class GenerateObservablePortAttribute : System.Attribute
    {
        public GenerateObservablePortAttribute() { }
    }
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=false, Inherited=false)]
    public sealed class GenerateSettersAttribute : System.Attribute
    {
        public GenerateSettersAttribute() { }
    }
    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple=false, Inherited=false)]
    public sealed class ObservablePortIgnoreAttribute : System.Attribute
    {
        public ObservablePortIgnoreAttribute() { }
    }
    [System.AttributeUsage(System.AttributeTargets.Property, AllowMultiple=false, Inherited=false)]
    public sealed class SetterIgnoreAttribute : System.Attribute
    {
        public SetterIgnoreAttribute() { }
    }
}
