namespace Functorium.Adapters.SourceGenerator.Abstractions;

public static class Constants
{
    public const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
";

    //public const string ClassEntityName = "class";

    //public static class TrackingNames
    //{
    //    public const string InitialValues = nameof(InitialValues);
    //    //public const string NotNullValues = nameof(NotNullValues);
    //}
}
