//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by PublicApiGenerator.
//     Assembly: Functorium.Testing
//     Generated at: 2026-04-07 오후 9:05:44
// </auto-generated>
//------------------------------------------------------------------------------

namespace Functorium.Testing.Actions.SourceGenerators
{
    public static class SourceGeneratorTestRunner
    {
        public static string? Generate<TGenerator>(this TGenerator generator, string sourceCode)
            where TGenerator : Microsoft.CodeAnalysis.IIncrementalGenerator, new () { }
        [return: System.Runtime.CompilerServices.TupleElementNames(new string[] {
                "GeneratedCode",
                "Diagnostics"})]
        public static System.ValueTuple<string?, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic>> GenerateWithDiagnostics<TGenerator>(this TGenerator generator, string sourceCode)
            where TGenerator : Microsoft.CodeAnalysis.IIncrementalGenerator, new () { }
    }
}
namespace Functorium.Testing.Arrangements.Effects
{
    public static class FinTFactory
    {
        public static LanguageExt.FinT<LanguageExt.IO, T> Fail<T>(LanguageExt.Common.Error error) { }
        public static LanguageExt.FinT<LanguageExt.IO, T> Succ<T>(T value) { }
    }
}
namespace Functorium.Testing.Arrangements.Hosting
{
    public class HostTestFixture<TProgram> : System.IAsyncDisposable, Xunit.IAsyncLifetime
        where TProgram :  class
    {
        public HostTestFixture() { }
        public System.Net.Http.HttpClient Client { get; }
        protected virtual string EnvironmentName { get; }
        public System.IServiceProvider Services { get; }
        protected virtual void ConfigureHost(Microsoft.AspNetCore.Hosting.IWebHostBuilder builder) { }
        public virtual System.Threading.Tasks.ValueTask DisposeAsync() { }
        protected virtual string GetTestProjectPath() { }
        public virtual System.Threading.Tasks.ValueTask InitializeAsync() { }
    }
}
namespace Functorium.Testing.Arrangements.Loggers
{
    public class TestSink : Serilog.Core.ILogEventSink
    {
        public TestSink(System.Collections.Generic.List<Serilog.Events.LogEvent> logEvents) { }
        public void Emit(Serilog.Events.LogEvent logEvent) { }
    }
}
namespace Functorium.Testing.Arrangements.Logging
{
    public sealed class LogTestContext : System.IDisposable
    {
        public LogTestContext() { }
        public LogTestContext(Serilog.Events.LogEventLevel minimumLevel) { }
        public LogTestContext(Serilog.Events.LogEventLevel minimumLevel, bool enrichFromLogContext) { }
        public int LogCount { get; }
        public System.Collections.Generic.IReadOnlyList<Serilog.Events.LogEvent> LogEvents { get; }
        public void Clear() { }
        public Microsoft.Extensions.Logging.ILogger<T> CreateLogger<T>() { }
        public void Dispose() { }
        public System.Collections.Generic.IEnumerable<object> ExtractAllLogData() { }
        public object ExtractFirstLogData() { }
        public object ExtractLogDataAt(int index) { }
        public object ExtractSecondLogData() { }
        public Serilog.Events.LogEvent GetFirstLog() { }
        public Serilog.Events.LogEvent GetLogAt(int index) { }
        public System.Collections.Generic.IReadOnlyList<Serilog.Events.LogEvent> GetLogsByLevel(Serilog.Events.LogEventLevel level) { }
        public Serilog.Events.LogEvent GetSecondLog() { }
    }
    public class StructuredTestLogger<T> : Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.ILogger<T>
    {
        public StructuredTestLogger(Serilog.ILogger serilogLogger) { }
        public System.IDisposable? BeginScope<TState>(TState state)
            where TState :  notnull { }
        public bool IsEnabled(Microsoft.Extensions.Logging.LogLevel logLevel) { }
        public void Log<TState>(Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, TState state, System.Exception? exception, System.Func<TState, System.Exception?, string> formatter) { }
    }
}
namespace Functorium.Testing.Arrangements.ScheduledJobs
{
    public sealed class JobCompletionListener : Quartz.IJobListener
    {
        public JobCompletionListener() { }
        public string Name { get; }
        public System.Threading.Tasks.Task JobExecutionVetoed(Quartz.IJobExecutionContext context, System.Threading.CancellationToken cancellationToken = default) { }
        public System.Threading.Tasks.Task JobToBeExecuted(Quartz.IJobExecutionContext context, System.Threading.CancellationToken cancellationToken = default) { }
        public System.Threading.Tasks.Task JobWasExecuted(Quartz.IJobExecutionContext context, Quartz.JobExecutionException? jobException, System.Threading.CancellationToken cancellationToken = default) { }
        public void Reset() { }
        public System.Threading.Tasks.Task<Functorium.Testing.Arrangements.ScheduledJobs.JobExecutionResult> WaitForJobCompletionAsync(string jobName, System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken = default) { }
    }
    public sealed class JobExecutionResult : System.IEquatable<Functorium.Testing.Arrangements.ScheduledJobs.JobExecutionResult>
    {
        public JobExecutionResult(string JobName, bool Success, object? Result, Quartz.JobExecutionException? Exception, System.TimeSpan ExecutionTime) { }
        public Quartz.JobExecutionException? Exception { get; init; }
        public System.TimeSpan ExecutionTime { get; init; }
        public string JobName { get; init; }
        public object? Result { get; init; }
        public bool Success { get; init; }
    }
    public class QuartzTestFixture<TProgram> : System.IAsyncDisposable, Xunit.IAsyncLifetime
        where TProgram :  class
    {
        public QuartzTestFixture() { }
        protected virtual string EnvironmentName { get; }
        public Functorium.Testing.Arrangements.ScheduledJobs.JobCompletionListener JobListener { get; }
        public Quartz.IScheduler Scheduler { get; }
        public System.IServiceProvider Services { get; }
        protected virtual void ConfigureWebHost(Microsoft.AspNetCore.Hosting.IWebHostBuilder builder) { }
        public virtual System.Threading.Tasks.ValueTask DisposeAsync() { }
        public System.Threading.Tasks.Task<Functorium.Testing.Arrangements.ScheduledJobs.JobExecutionResult> ExecuteJobOnceAsync<TJob>(System.TimeSpan timeout)
            where TJob : Quartz.IJob { }
        public System.Threading.Tasks.Task<Functorium.Testing.Arrangements.ScheduledJobs.JobExecutionResult> ExecuteJobOnceAsync<TJob>(string jobName, string jobGroup, System.TimeSpan timeout)
            where TJob : Quartz.IJob { }
        protected virtual string GetTestProjectPath() { }
        public virtual System.Threading.Tasks.ValueTask InitializeAsync() { }
    }
}
namespace Functorium.Testing
{
    public static class AssemblyReference
    {
        public static readonly System.Reflection.Assembly Assembly;
    }
}
namespace Functorium.Testing.Assertions.ArchitectureRules
{
    public static class ArchitectureValidationEntryPoint
    {
        public static Functorium.Testing.Assertions.ArchitectureRules.ValidationResultSummary ValidateAllClasses(this ArchUnitNET.Domain.IObjectProvider<ArchUnitNET.Domain.Class> classes, ArchUnitNET.Domain.Architecture architecture, System.Action<Functorium.Testing.Assertions.ArchitectureRules.ClassValidator> validationRule, bool verbose = false) { }
        public static Functorium.Testing.Assertions.ArchitectureRules.ValidationResultSummary ValidateAllInterfaces(this ArchUnitNET.Domain.IObjectProvider<ArchUnitNET.Domain.Interface> interfaces, ArchUnitNET.Domain.Architecture architecture, System.Action<Functorium.Testing.Assertions.ArchitectureRules.InterfaceValidator> validationRule, bool verbose = false) { }
    }
    public sealed class ArchitectureViolationException : System.Exception
    {
        public ArchitectureViolationException(string ruleName, System.Collections.Generic.IReadOnlyList<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation> violations) { }
        public string RuleName { get; }
        public System.Collections.Generic.IReadOnlyList<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation> Violations { get; }
    }
    public sealed class ClassValidator : Functorium.Testing.Assertions.ArchitectureRules.TypeValidator<ArchUnitNET.Domain.Class, Functorium.Testing.Assertions.ArchitectureRules.ClassValidator>
    {
        public ClassValidator(ArchUnitNET.Domain.Architecture architecture, ArchUnitNET.Domain.Class targetClass) { }
        protected override string TypeKind { get; }
        protected override System.Collections.Generic.IEnumerable<ArchUnitNET.Domain.IMember> GetSearchableMembers() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireAbstract() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireAllPrivateConstructors() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireAttribute(string attributeName) { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireImmutable() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireInherits(System.Type baseType) { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireInternal() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNestedClass(string nestedClassName, System.Action<Functorium.Testing.Assertions.ArchitectureRules.ClassValidator>? nestedClassValidation = null) { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNestedClassIfExists(string nestedClassName, System.Action<Functorium.Testing.Assertions.ArchitectureRules.ClassValidator>? nestedClassValidation = null) { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNoInstanceFields(params string[] excludeFieldTypeContaining) { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNoPublicSetters() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNotAbstract() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNotRecord() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNotSealed() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireNotStatic() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireOnlyPrimitiveProperties(params string[] additionalAllowedTypePrefixes) { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequirePrivateAnyParameterlessConstructor() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequirePublic() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireRecord() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireSealed() { }
        public Functorium.Testing.Assertions.ArchitectureRules.ClassValidator RequireStatic() { }
    }
    public sealed class CompositeArchRule<TType> : Functorium.Testing.Assertions.ArchitectureRules.IArchRule<TType>
        where TType : ArchUnitNET.Domain.IType
    {
        public CompositeArchRule(params Functorium.Testing.Assertions.ArchitectureRules.IArchRule<TType>[] rules) { }
        public CompositeArchRule(System.Collections.Generic.IEnumerable<Functorium.Testing.Assertions.ArchitectureRules.IArchRule<TType>> rules) { }
        public string Description { get; }
        public System.Collections.Generic.IReadOnlyList<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation> Validate(TType target, ArchUnitNET.Domain.Architecture architecture) { }
    }
    public sealed class DelegateArchRule<TType> : Functorium.Testing.Assertions.ArchitectureRules.IArchRule<TType>
        where TType : ArchUnitNET.Domain.IType
    {
        public DelegateArchRule(string description, System.Func<TType, ArchUnitNET.Domain.Architecture, System.Collections.Generic.IReadOnlyList<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation>> validate) { }
        public string Description { get; }
        public System.Collections.Generic.IReadOnlyList<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation> Validate(TType target, ArchUnitNET.Domain.Architecture architecture) { }
    }
    public interface IArchRule<in TType>
        where in TType : ArchUnitNET.Domain.IType
    {
        string Description { get; }
        System.Collections.Generic.IReadOnlyList<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation> Validate(TType target, ArchUnitNET.Domain.Architecture architecture);
    }
    public sealed class InterfaceValidator : Functorium.Testing.Assertions.ArchitectureRules.TypeValidator<ArchUnitNET.Domain.Interface, Functorium.Testing.Assertions.ArchitectureRules.InterfaceValidator>
    {
        public InterfaceValidator(ArchUnitNET.Domain.Architecture architecture, ArchUnitNET.Domain.Interface targetInterface) { }
        protected override string TypeKind { get; }
    }
    public sealed class MethodValidator
    {
        public MethodValidator(ArchUnitNET.Domain.MethodMember targetMethod, System.Collections.Generic.List<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation> violations) { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireAnyParameterTypeContaining(string typeNameFragment) { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireExtensionMethod() { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireFirstParameterTypeContaining(string typeNameFragment) { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireNotStatic() { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireNotVirtual() { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireParameterCount(int expectedCount) { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireParameterCountAtLeast(int minimumCount) { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireReturnType(System.Type returnType) { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireReturnTypeContaining(string typeNameFragment) { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireReturnTypeOfDeclaringClass() { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireReturnTypeOfDeclaringTopLevelClass() { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireStatic() { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireVirtual() { }
        public Functorium.Testing.Assertions.ArchitectureRules.MethodValidator RequireVisibility(ArchUnitNET.Domain.Visibility visibility) { }
    }
    public sealed class RuleViolation : System.IEquatable<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation>
    {
        public RuleViolation(string TargetName, string RuleName, string Description) { }
        public string Description { get; init; }
        public string RuleName { get; init; }
        public string TargetName { get; init; }
    }
    public abstract class TypeValidator<TType, TSelf>
        where TType : ArchUnitNET.Domain.IType
        where TSelf : Functorium.Testing.Assertions.ArchitectureRules.TypeValidator<TType, TSelf>
    {
        protected readonly ArchUnitNET.Domain.Architecture _architecture;
        protected readonly TType _target;
        protected TypeValidator(ArchUnitNET.Domain.Architecture architecture, TType target) { }
        protected TypeValidator(ArchUnitNET.Domain.Architecture architecture, TType target, Functorium.Testing.Assertions.ArchitectureRules.TypeValidator<TType, TSelf> parent) { }
        protected abstract string TypeKind { get; }
        protected void AddViolation(string description, [System.Runtime.CompilerServices.CallerMemberName] string ruleName = "") { }
        public TSelf Apply(Functorium.Testing.Assertions.ArchitectureRules.IArchRule<TType> rule) { }
        protected virtual System.Collections.Generic.IEnumerable<ArchUnitNET.Domain.IMember> GetSearchableMembers() { }
        public TSelf RequireAllMethods(System.Action<Functorium.Testing.Assertions.ArchitectureRules.MethodValidator> methodValidation) { }
        public TSelf RequireAllMethods(System.Func<ArchUnitNET.Domain.MethodMember, bool> filter, System.Action<Functorium.Testing.Assertions.ArchitectureRules.MethodValidator> methodValidation) { }
        public TSelf RequireImplements(System.Type interfaceType) { }
        public TSelf RequireImplementsGenericInterface(string genericInterfaceName) { }
        public TSelf RequireMethod(string methodName, System.Action<Functorium.Testing.Assertions.ArchitectureRules.MethodValidator> methodValidation) { }
        public TSelf RequireMethodIfExists(string methodName, System.Action<Functorium.Testing.Assertions.ArchitectureRules.MethodValidator> methodValidation) { }
        public TSelf RequireNameEndsWith(string suffix) { }
        public TSelf RequireNameMatching(string regexPattern) { }
        public TSelf RequireNameStartsWith(string prefix) { }
        public TSelf RequireNoDependencyOn(string typeNameContains) { }
        public virtual TSelf RequireProperty(string propertyName) { }
    }
    public sealed class ValidationResultSummary
    {
        public ValidationResultSummary() { }
        public void ThrowIfAnyFailures(string ruleName) { }
    }
}
namespace Functorium.Testing.Assertions.ArchitectureRules.Rules
{
    public sealed class ImmutabilityRule : Functorium.Testing.Assertions.ArchitectureRules.IArchRule<ArchUnitNET.Domain.Class>
    {
        public ImmutabilityRule() { }
        public string Description { get; }
        public System.Collections.Generic.IReadOnlyList<Functorium.Testing.Assertions.ArchitectureRules.RuleViolation> Validate(ArchUnitNET.Domain.Class target, ArchUnitNET.Domain.Architecture architecture) { }
    }
}
namespace Functorium.Testing.Assertions.ArchitectureRules.Suites
{
    public abstract class ApplicationArchitectureTestSuite
    {
        protected ApplicationArchitectureTestSuite() { }
        protected abstract string ApplicationNamespace { get; }
        protected abstract ArchUnitNET.Domain.Architecture Architecture { get; }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\ApplicationArchitectureTestSuite.cs", 34)]
        public void Command_ShouldHave_UsecaseNestedClass() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\ApplicationArchitectureTestSuite.cs", 15)]
        public void Command_ShouldHave_ValidatorNestedClass() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\ApplicationArchitectureTestSuite.cs", 72)]
        public void Query_ShouldHave_UsecaseNestedClass() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\ApplicationArchitectureTestSuite.cs", 53)]
        public void Query_ShouldHave_ValidatorNestedClass() { }
    }
    public abstract class DomainArchitectureTestSuite
    {
        protected DomainArchitectureTestSuite() { }
        protected abstract ArchUnitNET.Domain.Architecture Architecture { get; }
        protected abstract string DomainNamespace { get; }
        protected virtual string[] DomainServiceAllowedFieldTypes { get; }
        protected virtual System.Collections.Generic.IReadOnlyList<System.Type> ValueObjectExcludeFromFactoryMethods { get; }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 30)]
        public void AggregateRoot_ShouldBe_PublicSealedClass() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 93)]
        public void AggregateRoot_ShouldHave_AllPrivateConstructors() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 50)]
        public void AggregateRoot_ShouldHave_CreateAndCreateFromValidated() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 75)]
        public void AggregateRoot_ShouldHave_GenerateEntityIdAttribute() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 273)]
        public void DomainEvent_ShouldBe_SealedRecord() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 291)]
        public void DomainEvent_ShouldHave_EventSuffix() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 416)]
        public void DomainService_PublicMethods_ShouldReturn_Fin() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 364)]
        public void DomainService_ShouldBe_PublicSealed() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 382)]
        public void DomainService_ShouldBe_Stateless() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 437)]
        public void DomainService_ShouldNotBe_Record() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 399)]
        public void DomainService_ShouldNotDependOn_IObservablePort() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 112)]
        public void Entity_ShouldBe_PublicSealedClass() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 159)]
        public void Entity_ShouldHave_AllPrivateConstructors() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 133)]
        public void Entity_ShouldHave_CreateAndCreateFromValidated() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 310)]
        public void Specification_ShouldBe_PublicSealed() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 329)]
        public void Specification_ShouldInherit_SpecificationBase() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 347)]
        public void Specification_ShouldResideIn_DomainLayer() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 200)]
        public void ValueObject_ShouldBe_Immutable() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 180)]
        public void ValueObject_ShouldBe_PublicSealedWithPrivateConstructors() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 218)]
        public void ValueObject_ShouldHave_CreateFactoryMethod() { }
        [Xunit.Fact("C:\\Workspace\\Github\\Functorium\\Src\\Functorium.Testing\\Assertions\\ArchitectureRule" +
            "s\\Suites\\DomainArchitectureTestSuite.cs", 244)]
        public void ValueObject_ShouldHave_ValidateMethod() { }
    }
}
namespace Functorium.Testing.Assertions.Errors
{
    public static class AdapterErrorAssertions
    {
        public static void ShouldBeAdapterError<TAdapter>(this LanguageExt.Common.Error error, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType) { }
        public static void ShouldBeAdapterError<TAdapter, T>(this LanguageExt.Fin<T> fin, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType) { }
        public static void ShouldBeAdapterError<TAdapter, TValue>(this LanguageExt.Common.Error error, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldBeAdapterError<TAdapter, T, TValue>(this LanguageExt.Fin<T> fin, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldBeAdapterError<TAdapter, T1, T2>(this LanguageExt.Common.Error error, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2)
            where T1 :  notnull
            where T2 :  notnull { }
        public static void ShouldBeAdapterError<TAdapter, T1, T2, T3>(this LanguageExt.Common.Error error, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2, T3 expectedValue3)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static void ShouldBeAdapterExceptionalError<TAdapter>(this LanguageExt.Common.Error error, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType) { }
        public static void ShouldBeAdapterExceptionalError<TAdapter, TException>(this LanguageExt.Common.Error error, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType)
            where TException : System.Exception { }
        public static void ShouldBeAdapterExceptionalError<TAdapter, T>(this LanguageExt.Fin<T> fin, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType) { }
        public static void ShouldHaveAdapterError<TAdapter, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType) { }
        public static void ShouldHaveAdapterError<TAdapter, T, TValue>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldHaveAdapterError<TAdapter, T, T1, T2>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2)
            where T1 :  notnull
            where T2 :  notnull { }
        public static void ShouldHaveAdapterError<TAdapter, T, T1, T2, T3>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2, T3 expectedValue3)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static void ShouldHaveAdapterErrors<TAdapter, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, params Functorium.Adapters.Errors.AdapterErrorType[] expectedErrorTypes) { }
        public static void ShouldHaveOnlyAdapterError<TAdapter, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Adapters.Errors.AdapterErrorType expectedErrorType) { }
    }
    public static class ApplicationErrorAssertions
    {
        public static void ShouldBeApplicationError<TUsecase>(this LanguageExt.Common.Error error, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType) { }
        public static void ShouldBeApplicationError<TUsecase, T>(this LanguageExt.Fin<T> fin, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType) { }
        public static void ShouldBeApplicationError<TUsecase, TValue>(this LanguageExt.Common.Error error, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldBeApplicationError<TUsecase, T, TValue>(this LanguageExt.Fin<T> fin, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldBeApplicationError<TUsecase, T1, T2>(this LanguageExt.Common.Error error, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2)
            where T1 :  notnull
            where T2 :  notnull { }
        public static void ShouldBeApplicationError<TUsecase, T1, T2, T3>(this LanguageExt.Common.Error error, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2, T3 expectedValue3)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static void ShouldHaveApplicationError<TUsecase, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType) { }
        public static void ShouldHaveApplicationError<TUsecase, T, TValue>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldHaveApplicationError<TUsecase, T, T1, T2>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2)
            where T1 :  notnull
            where T2 :  notnull { }
        public static void ShouldHaveApplicationError<TUsecase, T, T1, T2, T3>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2, T3 expectedValue3)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static void ShouldHaveApplicationErrors<TUsecase, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, params Functorium.Applications.Errors.ApplicationErrorType[] expectedErrorTypes) { }
        public static void ShouldHaveOnlyApplicationError<TUsecase, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Applications.Errors.ApplicationErrorType expectedErrorType) { }
    }
    public static class DomainErrorAssertions
    {
        public static void ShouldBeDomainError<TDomain>(this LanguageExt.Common.Error error, Functorium.Domains.Errors.DomainErrorType expectedErrorType) { }
        public static void ShouldBeDomainError<TDomain, T>(this LanguageExt.Fin<T> fin, Functorium.Domains.Errors.DomainErrorType expectedErrorType) { }
        public static void ShouldBeDomainError<TDomain, TValue>(this LanguageExt.Common.Error error, Functorium.Domains.Errors.DomainErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldBeDomainError<TDomain, T, TValue>(this LanguageExt.Fin<T> fin, Functorium.Domains.Errors.DomainErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldBeDomainError<TDomain, T1, T2>(this LanguageExt.Common.Error error, Functorium.Domains.Errors.DomainErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2)
            where T1 :  notnull
            where T2 :  notnull { }
        public static void ShouldBeDomainError<TDomain, T1, T2, T3>(this LanguageExt.Common.Error error, Functorium.Domains.Errors.DomainErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2, T3 expectedValue3)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static void ShouldHaveDomainError<TDomain, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Domains.Errors.DomainErrorType expectedErrorType) { }
        public static void ShouldHaveDomainError<TDomain, T, TValue>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Domains.Errors.DomainErrorType expectedErrorType, TValue expectedCurrentValue)
            where TValue :  notnull { }
        public static void ShouldHaveDomainError<TDomain, T, T1, T2>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Domains.Errors.DomainErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2)
            where T1 :  notnull
            where T2 :  notnull { }
        public static void ShouldHaveDomainError<TDomain, T, T1, T2, T3>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Domains.Errors.DomainErrorType expectedErrorType, T1 expectedValue1, T2 expectedValue2, T3 expectedValue3)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static void ShouldHaveDomainErrors<TDomain, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, params Functorium.Domains.Errors.DomainErrorType[] expectedErrorTypes) { }
        public static void ShouldHaveOnlyDomainError<TDomain, T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, Functorium.Domains.Errors.DomainErrorType expectedErrorType) { }
    }
    public static class ErrorAssertionHelpers
    {
        public static System.Collections.Generic.IReadOnlyList<LanguageExt.Common.Error> get_Errors<T>(LanguageExt.Validation<LanguageExt.Common.Error, T> validation)
            where T :  notnull { }
        extension(LanguageExt.Common.Error error)
        {
            public string? ErrorCode { get; }
            public bool HasErrorCode { get; }
        }
        extension<Error>(LanguageExt.Validation<LanguageExt.Common.Error, T> validation)
            where Error :  notnull
        {
            public System.Collections.Generic.IReadOnlyList<LanguageExt.Common.Error> Errors { get; }
        }
    }
    public static class ErrorCodeAssertions
    {
        public static void ShouldBeErrorCodeExpected(this LanguageExt.Common.Error error, string expectedErrorCode, string expectedCurrentValue) { }
        public static void ShouldBeErrorCodeExpected<T>(this LanguageExt.Common.Error error, string expectedErrorCode, T expectedCurrentValue)
            where T :  notnull { }
        public static void ShouldBeErrorCodeExpected<T>(this LanguageExt.Common.Error error, string expectedErrorCode, System.Func<T, bool> valuePredicate, string? customMessage = null)
            where T :  notnull { }
        public static void ShouldBeErrorCodeExpected<T1, T2>(this LanguageExt.Common.Error error, string expectedErrorCode, T1 expectedValue1, T2 expectedValue2)
            where T1 :  notnull
            where T2 :  notnull { }
        public static void ShouldBeErrorCodeExpected<T1, T2, T3>(this LanguageExt.Common.Error error, string expectedErrorCode, T1 expectedValue1, T2 expectedValue2, T3 expectedValue3)
            where T1 :  notnull
            where T2 :  notnull
            where T3 :  notnull { }
        public static void ShouldBeExceptional(this LanguageExt.Common.Error error) { }
        public static void ShouldBeExpected(this LanguageExt.Common.Error error) { }
        public static void ShouldBeInvalid<T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, System.Action<LanguageExt.Seq<LanguageExt.Common.Error>> errorsAssertion) { }
        public static T ShouldBeValid<T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation) { }
        public static void ShouldContainErrorCode<T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, string expectedErrorCode) { }
        public static void ShouldContainErrorCodes<T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, params string[] expectedErrorCodes) { }
        public static void ShouldContainOnlyErrorCode<T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, string expectedErrorCode) { }
        public static void ShouldFail<T>(this LanguageExt.Fin<T> fin) { }
        public static void ShouldFail<T>(this LanguageExt.Fin<T> fin, System.Action<LanguageExt.Common.Error> errorAssertion) { }
        public static void ShouldFailWithErrorCode<T>(this LanguageExt.Fin<T> fin, string expectedErrorCode) { }
        public static Functorium.Abstractions.Errors.IHasErrorCode ShouldHaveErrorCode(this LanguageExt.Common.Error error) { }
        public static void ShouldHaveErrorCode(this LanguageExt.Common.Error error, string expectedErrorCode) { }
        public static void ShouldHaveErrorCode(this LanguageExt.Common.Error error, System.Func<string, bool> predicate, string? customMessage = null) { }
        public static void ShouldHaveErrorCodeStartingWith(this LanguageExt.Common.Error error, string prefix) { }
        public static T ShouldSucceed<T>(this LanguageExt.Fin<T> fin) { }
        public static void ShouldSucceed<T>(this LanguageExt.Fin<T> fin, System.Func<T, bool> predicate, string? customMessage = null) { }
        public static void ShouldSucceedWith<T>(this LanguageExt.Fin<T> fin, T expectedValue) { }
    }
    public static class ErrorCodeExceptionalAssertions
    {
        public static void ShouldBeErrorCodeExceptional(this LanguageExt.Common.Error error, string expectedErrorCode) { }
        public static void ShouldBeErrorCodeExceptional(this LanguageExt.Common.Error error, string expectedErrorCode, System.Action<System.Exception> exceptionAssertion) { }
        public static void ShouldBeErrorCodeExceptional<TException>(this LanguageExt.Common.Error error, string expectedErrorCode)
            where TException : System.Exception { }
        public static void ShouldContainException<T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, string expectedErrorCode) { }
        public static void ShouldContainException<T, TException>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, string expectedErrorCode)
            where TException : System.Exception { }
        public static void ShouldContainOnlyException<T>(this LanguageExt.Validation<LanguageExt.Common.Error, T> validation, string expectedErrorCode) { }
        public static void ShouldFailWithException<T>(this LanguageExt.Fin<T> fin, string expectedErrorCode) { }
        public static void ShouldFailWithException<T>(this LanguageExt.Fin<T> fin, string expectedErrorCode, System.Action<System.Exception> exceptionAssertion) { }
        public static void ShouldFailWithException<T, TException>(this LanguageExt.Fin<T> fin, string expectedErrorCode)
            where TException : System.Exception { }
        public static void ShouldWrapException<TException>(this LanguageExt.Common.Error error, string expectedErrorCode, string? expectedMessage = null)
            where TException : System.Exception { }
    }
}
namespace Functorium.Testing.Assertions.Logging
{
    public static class LogEventPropertyExtractor
    {
        public static object ExtractLogData(Serilog.Events.LogEvent logEvent) { }
        public static System.Collections.Generic.IEnumerable<object> ExtractLogData(System.Collections.Generic.IEnumerable<Serilog.Events.LogEvent> logEvents) { }
        public static object ExtractValue(Serilog.Events.LogEventPropertyValue propertyValue) { }
    }
    public static class LogEventPropertyValueConverter
    {
        public static object ToAnonymousObject(Serilog.Events.LogEventPropertyValue value) { }
    }
    public sealed class SerilogTestPropertyValueFactory : Serilog.Core.ILogEventPropertyValueFactory
    {
        public SerilogTestPropertyValueFactory() { }
        public Serilog.Events.LogEventPropertyValue CreatePropertyValue(object? value, bool destructureObjects = false) { }
    }
}
