using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DevelopmentWorkflow.Generator;

[Generator]
public class WorkflowGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("AutoInfoAttribute.g.cs", """
                // <auto-generated/>
                namespace DevelopmentWorkflow.Generated;

                [System.AttributeUsage(System.AttributeTargets.Class)]
                public class AutoInfoAttribute : System.Attribute { }
                """);
        });

        var pipeline = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "DevelopmentWorkflow.Generated.AutoInfoAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                    var members = symbol.GetMembers()
                        .OfType<IMethodSymbol>()
                        .Where(m => m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public)
                        .Select(m => m.Name)
                        .ToArray();
                    return (symbol.Name, Ns: symbol.ContainingNamespace.ToDisplayString(), Members: members);
                });

        context.RegisterSourceOutput(pipeline, static (ctx, data) =>
        {
            var methodList = string.Join(", ", data.Members.Select(m => $"\"{m}\""));
            ctx.AddSource($"{data.Name}_Info.g.cs", $$"""
                // <auto-generated/>
                namespace {{data.Ns}};

                public partial class {{data.Name}}
                {
                    public static string TypeName => "{{data.Name}}";
                    public static string[] PublicMethods => [{{methodList}}];
                }
                """);
        });
    }
}
