global using LanguageExt;
global using LanguageExt.Common;
global using static LanguageExt.Prelude;
global using Xunit;
global using Shouldly;
global using NSubstitute;
global using Functorium.Applications.Cqrs;
global using Functorium.Adapters.Observabilities.Pipelines;
global using Cqrs02Pipeline.Demo;
global using Cqrs02Pipeline.Demo.Domain;
global using Cqrs02Pipeline.Demo.Usecases;
